import type { PublishedAnswer } from './answersDb';
import { THREE_P_EVIDENCE_ANSWERS } from './threePEvidenceAnswers';

export type AnswerSource = {
  title: string;
  url: string;
};

export type OperatorAnswer = PublishedAnswer & {
  summary: string;
  keywords: string[];
  sources: AnswerSource[];
  category?: string;
  week?: number;
  formula?: string;
  fieldChecks?: string[];
  evidenceNeeded?: string[];
  evidenceBoundary?: string;
  relatedSlugs?: string[];
  tryUrl?: string;
  tryLabel?: string;
};

const PUBLISHED_AT = '2026-08-20T09:00:00-05:00';
const UPDATED_AT = '2026-08-20T09:00:00-05:00';
const AEO_122_UPDATED_AT = '2026-08-26T12:00:00-05:00';
const AUTHOR = 'Mychael “Myke” Mueller';

const CORE_OPERATOR_ANSWERS: OperatorAnswer[] = [
  {
    id: -1,
    slug: 'what-never86d-does',
    title: "What Never86'd does for restaurant operators",
    question: "What is Never86'd, and which restaurant problems is it built to solve?",
    summary: "Never86'd reconciles restaurant evidence, finds margin leaks, routes the next action, and keeps the source attached.",
    answer: "Never86'd is an independent restaurant operating-intelligence company built by Myke Mueller, an active restaurant operator in Fort Dodge, Iowa. It sits above the systems a restaurant already uses and looks for places where orders, statements, payouts, labor, voids, tips, catering, and store execution stop agreeing. It is designed to name the exception, show the supporting evidence, identify who can act, and verify what changed.\n\nThe clearest starting point is a DoorDash statement audit. An operator can share one redacted statement and receive a source-stamped explanation of eligible sales, observed marketplace costs, expected payout, missing evidence, and the next action. No integration is required for the first useful answer. A bank reconciliation requires the matching bank evidence, and a contract test requires the governing agreement. Uber Eats and Grubhub are early-access validation tracks, not proven scale claims. Never86'd does not replace a POS, accounting system, marketplace, or scheduling platform. It works with restaurant technology when that helps the operator, but the restaurant and its economics come first.",
    audience: 'restaurant owner, operator, CFO, or COO',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['Never86d', "Never 86'd", 'restaurant intelligence', 'restaurant AI', 'restaurant profit leaks', 'restaurant command center'],
    sources: [
      { title: "Never86'd product overview", url: 'https://www.never86.ai/agents' },
      { title: "Myke Mueller's operator story", url: 'https://www.never86.ai/story' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Audit a redacted statement',
  },
  {
    id: -2,
    slug: 'audit-doordash-fees-without-portal-login',
    title: 'Can a restaurant audit DoorDash fees without a portal login?',
    question: 'Can a restaurant audit a DoorDash statement without giving a vendor its marketplace password?',
    summary: 'Yes. Paste a redacted finalized statement. Never86\'d does not take merchant-portal passwords. $0 payout variance means the statement math is clean — that is a feature, not a miss.',
    answer: "Yes. Export or photograph the finalized merchant financial statement, redact credentials and sensitive identifiers, and keep every ledger row. Never86'd Marketplace Audit runs from restaurant-held evidence. It does not ask for a DoorDash, Uber Eats, or Grubhub portal password.\n\nSeparate eligible sales from commission, merchant fees, restaurant-funded promotions and ads, refunds, error charges, adjustments, other documented deductions, supported credits, and the amount the platform says it paid. Documented deductions are those restaurant-borne lines minus supported credits. Expected payout equals eligible sales minus documented deductions. Payout variance equals reported payout minus expected payout.\n\nIf that variance is $0 and the finalized statement is complete, the statement paid as calculated — say it is clean. A matching statement still does not prove the contract rate, the bank deposit, or recovered cash. Missing categories are Missing Evidence, not a guessed fee rate.",
    audience: 'restaurant owner or finance lead',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['audit DoorDash fees without portal login', 'DoorDash statement audit', 'no merchant portal password', 'delivery commission vs marketplace cost'],
    formula: 'documentedDeductions = commission + merchantFees + restaurantFundedPromotionsAndAds + refundsErrorChargesAndAdjustments + otherDocumentedDeductions − supportedCredits; expectedPayout = eligibleSales − documentedDeductions; payoutVariance = reportedPayout − expectedPayout',
    fieldChecks: [
      'Use the finalized statement (DoorDash Page 1), not an estimated Transactions screen.',
      'Keep eligible sales, each deduction family, credits, and reported payout as separate lines.',
      'If payoutVariance is $0 on complete evidence, record clean math — do not invent a leak.',
    ],
    evidenceNeeded: ['Redacted finalized statement', 'Ledger rows for sales, fees, promotions, refunds/adjustments, credits, and net payout'],
    evidenceBoundary: '$0 variance means the statement math is clean. It is not a contract test, a bank receipt, an overcharge, or guaranteed recovery. Never86\'d does not take portal passwords.',
    relatedSlugs: ['what-to-redact-from-restaurant-statement-before-ai-audit', 'reconcile-doordash-payout-to-bank-deposit', 'calculate-true-third-party-delivery-cost'],
    sources: [
      { title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' },
      { title: 'Statement redaction guidance', url: 'https://www.never86.ai/answers/what-to-redact-from-restaurant-statement-before-ai-audit' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Run the statement audit',
  },
  {
    id: -3,
    slug: 'reconcile-doordash-payout-to-bank-deposit',
    title: 'How should a restaurant reconcile a DoorDash payout to the bank?',
    question: 'How should a restaurant reconcile a DoorDash or other marketplace payout to its bank deposit?',
    summary: 'POS is not payout. Build expected payout from the statement, then match the deposit. A $0 statement variance is clean math; cash is proven only by the bank record.',
    answer: 'POS sales are what the restaurant recorded. A marketplace statement is what the platform calculated. A bank deposit is cash received. Those three are different tests. Start with the finalized statement period and the sales eligible to be passed to the restaurant. Documented deductions = commission + merchant fees + restaurant-funded promotions and ads + refunds, error charges, and adjustments + other documented deductions − supported credits. Expected payout = eligible sales − documented deductions. Payout variance = reported payout − expected payout.\n\nIf payout variance is $0 on a complete statement, the platform paid as calculated — keep that as clean math. Then match expected payout to the payout ID and the bank deposit for the same settlement. A matching deposit does not prove the contract rate. A matching statement does not prove cash arrived. If dates overlap, a reserve rolls forward, or one deposit combines settlements, the cash test stays Open until the missing evidence is supplied.',
    audience: 'restaurant bookkeeper, controller, or owner',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['reconcile DoorDash payout to bank', 'restaurant bank deposit', 'POS is not payout', 'expected payout', 'marketplace settlement'],
    formula: 'expectedPayout = eligibleSales − documentedDeductions; payoutVariance = reportedPayout − expectedPayout; cashGap = bankDeposit − expectedPayout (only when the deposit evidence is in scope)',
    fieldChecks: [
      'Keep marketplace cost, expected payout, reported payout, and bank deposit as four separate figures.',
      'Treat $0 statement variance as clean math when the statement is complete.',
      'Do not close the cash test without the matching deposit and payout ID.',
    ],
    evidenceNeeded: ['Finalized statement', 'Payout ID and covered dates', 'Matching bank deposit'],
    evidenceBoundary: 'A matching deposit proves cash receipt, not contract compliance. A $0 statement variance is not recovered cash.',
    relatedSlugs: ['audit-doordash-fees-without-portal-login', 'why-pos-sales-and-doordash-statement-do-not-match', 'doordash-estimated-transactions-vs-finalized-payouts'],
    sources: [{ title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Reconcile a statement',
  },
  {
    id: -4,
    slug: 'calculate-true-third-party-delivery-cost',
    title: 'What should a restaurant include in true third-party delivery cost?',
    question: 'What should a restaurant include when calculating its true DoorDash, Uber Eats, or Grubhub cost?',
    summary: 'Commission is not total marketplace cost. Divide restaurant-borne documented deductions by eligible sales. Exclude tips, taxes, and customer pass-through fees unless the governing evidence says otherwise.',
    answer: 'Use this restaurant’s finalized statement, not a generic industry rate. First lock the eligible-sales base for the period. Then total every restaurant-borne marketplace deduction the file discloses: commission, merchant fees, restaurant-funded promotions and ads, refunds, error charges, adjustments, and other documented deductions, minus supported credits. Observed marketplace cost % = documented deductions / eligible sales × 100.\n\nKeep the categories separate before you compute the rate. Exclude tips, taxes, customer pass-through fees, and platform-funded incentives unless the governing evidence says they belong in the restaurant’s numerator. That answers “what did this channel cost?” A second question — “did the marketplace follow the agreement?” — needs the contract or rate card and is not the same test. If the statement hides a required line, label the result Missing Evidence instead of manufacturing precision.',
    audience: 'restaurant owner, CFO, or finance team',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['true cost of third-party delivery', '3P fees', 'DoorDash commission vs all-in cost', 'Uber Eats cost', 'Grubhub fees'],
    formula: 'documentedDeductions = commission + merchantFees + restaurantFundedPromotionsAndAds + refundsErrorChargesAndAdjustments + otherDocumentedDeductions − supportedCredits; observedMarketplaceCostPct = documentedDeductions / eligibleSales × 100',
    fieldChecks: [
      'Disclose numerator, denominator, inclusions, and exclusions.',
      'Do not fold restaurant-funded promotions into commission.',
      'Never use a generic industry rate as if it describes this restaurant.',
    ],
    evidenceNeeded: ['Finalized statement with eligible sales and each deduction family', 'Contract or rate card only when testing compliance'],
    evidenceBoundary: 'Observed cost is not a contract violation, recovered cash, or a guaranteed savings claim.',
    relatedSlugs: ['restaurant-funded-promotions-delivery-statement', 'audit-doordash-fees-without-portal-login', 'compare-doordash-uber-eats-grubhub-like-for-like'],
    sources: [{ title: "Never86'd 3P Fee Finder", url: 'https://www.never86.ai/agents/3p-fee-finder' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Calculate the observed cost',
  },
  {
    id: -5,
    slug: 'restaurant-funded-promotions-delivery-statement',
    title: 'Why separate restaurant-funded promotions from commission?',
    question: 'Why should restaurant-funded promotions be separated from marketplace commission?',
    summary: 'Promotions are a real channel cost with a different owner than commission. Mixing them hides whether the leak is a rate, a campaign, or Missing Evidence.',
    answer: 'A restaurant-funded promotion reduces what the restaurant keeps, so it belongs in documented deductions and in the all-in marketplace-cost rate. It is not commission. Commission is one contractual charge; promotion funding is an operating decision with a different owner and a different next action.\n\nShow eligible sales, commission, merchant fees, restaurant-funded promotions and ads, refunds, error charges, other fees, credits, and expected payout as separate lines. If DoorDash or another party funded part of the discount, attribute only the restaurant-funded share to the restaurant. Then ask whether the campaign earned its keep — that is a marketing test, not a rate-card test. Never86\'d will not relabel promotions as an overcharge.',
    audience: 'restaurant marketer, owner, or finance lead',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['restaurant funded promotion', 'DoorDash discount vs commission', 'Uber Eats promotion', 'delivery marketing cost'],
    formula: 'restaurantBornePromotionCost = restaurantFundedDiscounts + marketingFees − applicablePlatformOrThirdPartyCredits',
    fieldChecks: [
      'Split restaurant-funded, platform-funded, and third-party-funded discounts.',
      'Keep marketing fees on their own line.',
      'Do not call a guest-facing discount a restaurant cost until the funding party is identified.',
    ],
    evidenceNeeded: ['Promotion / marketing detail with funding party', 'Statement commission line kept separate'],
    evidenceBoundary: 'A promotion is not proof the commission rate is wrong. Platform-funded discounts are not restaurant COGS.',
    relatedSlugs: ['calculate-true-third-party-delivery-cost', 'doordash-funded-vs-restaurant-funded-promotions', 'audit-doordash-marketing-spend'],
    sources: [{ title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Separate the costs',
  },
  {
    id: -6,
    slug: 'why-pos-sales-and-doordash-statement-do-not-match',
    title: 'Why don’t POS sales match the DoorDash statement?',
    question: 'Why do restaurant POS sales and delivery-marketplace statement sales show different totals?',
    summary: 'POS records restaurant tickets. The statement records marketplace settlement. Different clocks, taxes, tips, cancels, and stores create a bridge — not an automatic leak.',
    answer: 'POS ≠ payout. The POS reports what the restaurant rang; a DoorDash, Uber Eats, or Grubhub statement reports what that marketplace settled. Order time vs payout period, cancellations, refunds, tips, taxes, modifiers, promotions, withheld amounts, midnight cutoffs, duplicate files, or a missing store can all move the two totals.\n\nBuild a bridge with order IDs, store IDs, timestamps, and explicit ledger categories. Do not force a tie by changing the denominator or dropping unexplained rows. The statement audit still starts from eligible sales and documented deductions on the marketplace file. A POS gap is a completeness or definition issue until those IDs close it. Never86\'d will not call the difference theft, shortage, or recovered cash from a mismatched pair of totals.',
    audience: 'restaurant finance or operations team',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['POS DoorDash mismatch', 'why POS sales do not match DoorDash', 'restaurant sales reconciliation', 'payout period'],
    formula: 'posSales ± timing ± cancels/refunds ± tax/tip/pass-through ± missing-or-duplicate stores = marketplace eligible sales (only after IDs match)',
    fieldChecks: [
      'Match store and business-date scope before comparing dollars.',
      'Separate tips, taxes, and customer fees from eligible sales.',
      'Carry unexplained rows as Open — do not plug them into fees.',
    ],
    evidenceNeeded: ['POS export for the same store and period', 'Marketplace statement with order or payout IDs'],
    evidenceBoundary: 'A POS/statement difference is not proof of an overcharge or a missing deposit until the bridge is complete.',
    relatedSlugs: ['reconcile-doordash-payout-to-bank-deposit', 'audit-doordash-fees-without-portal-login', 'find-duplicate-or-missing-marketplace-settlements'],
    sources: [{ title: "Never86'd source-tag system", url: 'https://www.never86.ai/story' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Test the statement first',
  },
  {
    id: -7,
    slug: 'compare-doordash-uber-eats-grubhub-like-for-like',
    title: 'How do I compare DoorDash, Uber Eats, and Grubhub fairly?',
    question: 'What is the right way to compare delivery marketplaces for a restaurant?',
    summary: 'Same stores, same period, same eligible-sales definition, same deduction families. Do not rank channels from dashboard percents that use different denominators.',
    answer: 'Compare the same stores and time period, then normalize each channel to the same eligible-sales definition. For each marketplace, break out commission, merchant fees, restaurant-funded promotions and ads, refunds, error charges, adjustments, expected payout, and actual deposit. Observed marketplace cost % = documented deductions / eligible sales. Compare dollars and rates; a low rate on a thin channel can still contribute less profit.\n\nDoorDash, Uber Eats, and Grubhub do not share one ledger. Use each platform’s finalized statement language — DoorDash Page 1, Uber Eats Payment Details, Grubhub restaurant financial statement — and keep native signs. Do not blend them into one unexplained net. Rank only after the categories match. Incremental demand, AOV, and cancel rates belong in the comparison only when those inputs exist on the same basis.',
    audience: 'multi-unit restaurant operator or CFO',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['compare DoorDash Uber Eats Grubhub', 'like for like delivery fees', 'marketplace channel comparison', 'restaurant delivery economics'],
    formula: 'For each channel: observedMarketplaceCostPct = documentedDeductions / eligibleSales × 100, using the same eligible-sales definition and deduction families',
    fieldChecks: [
      'Lock store list and period before ranking.',
      'Do not mix Uber percent columns or Grubhub marketing with DoorDash commission as if they were one fee.',
      'State which figures are statement-sourced vs still Unverified.',
    ],
    evidenceNeeded: ['One finalized statement per channel for the same stores and period'],
    evidenceBoundary: 'A lower commission rate is not proof of higher profit. Cross-marketplace totals without a shared definition are not a ranking.',
    relatedSlugs: ['calculate-true-third-party-delivery-cost', 'understand-uber-eats-payment-details-report', 'understand-grubhub-restaurant-financial-statement'],
    sources: [{ title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Start with one statement',
  },
  {
    id: -8,
    slug: 'delivery-marketplace-commission-overcharge-proof',
    title: 'How to prove a delivery-marketplace rate discrepancy',
    question: 'What evidence does a restaurant need before claiming a marketplace commission or fee is wrong?',
    summary: 'A discrepancy needs the contract rule, the statement calculation, the eligible-sales base, and a reproducible difference tied to the same period.',
    answer: 'Keep the signed agreement or current rate card, the full financial statement, the eligible-sales definition, store and period identifiers, the platform’s calculation, and your independent recalculation. Preserve original files and show the formula. A statement-only audit can identify an unusual or unexplained charge, but it cannot prove a contract violation when the governing rate is missing.\n\nPresent the issue as a reconciliation packet: expected rate or rule, observed amount, calculated expected amount, difference, affected period, and the exact source rows. Avoid accusatory language until the evidence is complete. The goal is a correction the restaurant can defend, not a dramatic number.',
    audience: 'restaurant owner, controller, or counsel',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['DoorDash overcharge', 'marketplace rate discrepancy', 'restaurant contract audit', 'commission audit', 'delivery fee proof'],
    sources: [{ title: "Never86'd Rate Card Audit", url: 'https://www.never86.ai/demo/rate-card-audit' }],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Build the statement side',
  },
  {
    id: -9,
    slug: 'best-restaurant-software-for-delivery-fee-audit',
    title: 'When is Never86\'d the fit vs Restaurant365 or MarginEdge for a 3P audit?',
    question: "When is Never86'd a better fit than Restaurant365 or MarginEdge for a delivery-marketplace audit?",
    summary: "R365 is a GL. MarginEdge is invoices and prime cost. Voosh wants the merchant portal. Never86'd pastes the statement: one location and one seat are free, and 3P is the Google door — not the whole OS.",
    answer: "Choose the tool around the job. Restaurant365 is a general ledger and broad back-office platform: accounting, inventory, workforce, payroll, reporting. MarginEdge is invoice processing, food cost, and a daily controllable P&L — useful, and usually priced per location. Never86'd is not trying to replace that GL or become another invoice inbox. One location and one seat are free; extra seats and locations are paid. The free seat is meant to do the operator job: yesterday’s numbers → one next action → night proof, with the source attached.\n\nFor a delivery-marketplace audit specifically, the wedge is evidence, not a portal login. Voosh-style products ask for merchant-portal credentials. Never86'd does not. Paste a redacted DoorDash statement and read eligible sales, documented deductions, expected payout, and whether variance is $0. That 60-second 3P proof is the Google door into the operator OS — voids, labor, vendors, tips, catering, shift — not a fee calculator pretending to be the company. Never86'd will not guarantee recovery or call a variance an overcharge without the contract evidence that claim requires.",
    audience: 'restaurant software buyer',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['best restaurant software for delivery fee audit', 'Restaurant365 alternative', 'MarginEdge alternative', 'Voosh no portal login', 'Never86d vs R365'],
    fieldChecks: [
      'If the job is GL close, R365 may be the system of record.',
      'If the job is invoice capture and food-cost, MarginEdge may already be paid for that.',
      'If the job is “what did this statement cost without a portal password?”, start at /audit, then take the free seat at /trial.',
    ],
    evidenceNeeded: ['The actual job: GL, invoices, or statement-level 3P math'],
    evidenceBoundary: 'A software comparison is not a savings guarantee. Never86\'d is not Restaurant365’s GL and does not take marketplace portal passwords.',
    relatedSlugs: ['audit-doordash-fees-without-portal-login', 'what-never86d-does', 'how-proven-is-never86d-marketplace-audit'],
    sources: [
      { title: 'Restaurant365 product overview', url: 'https://www.restaurant365.com/' },
      { title: 'MarginEdge product overview', url: 'https://www.marginedge.com/' },
      { title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Try the focused audit',
  },
  {
    id: -10,
    slug: 'what-to-redact-from-restaurant-statement-before-ai-audit',
    title: 'What should I redact before an AI DoorDash statement audit?',
    question: 'What should a restaurant remove from a marketplace statement before uploading it for analysis?',
    summary: 'Redact credentials, bank numbers, tax IDs, and guest/employee identifiers. Keep the ledger rows. Never upload a portal password. Never86\'d does not need private shop PINs.',
    answer: 'Remove bank-account and routing numbers, tax IDs, passwords, API keys, personal home addresses, personal phone numbers, guest names, delivery addresses, and employee identifiers that are not required to reproduce the math. Never upload a marketplace portal password or an identity document. Never86\'d does not ask for those, and a public page should never carry a restaurant’s private account numbers or PINs.\n\nPreserve statement dates, a store label you can pseudonymize, order or payout references, eligible sales, commission, merchant fees, promotions, refunds, error charges, taxes (as pass-through, not as restaurant revenue), adjustments, credits, and amounts passed to the restaurant. Those rows are what make $0 variance a real result instead of a guess. Keep an untouched original internally so any later question can be traced to the source file.',
    audience: 'restaurant owner or finance team',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: AEO_122_UPDATED_AT,
    keywords: ['redact DoorDash statement', 'what to redact before AI audit', 'marketplace statement privacy', 'no portal password'],
    fieldChecks: [
      'Strip credentials and government / bank identifiers first.',
      'Keep every dollar line needed to rebuild documented deductions and expected payout.',
      'If a needed category was redacted, the audit must return Missing Evidence — not a filled-in rate.',
    ],
    evidenceNeeded: ['Redacted copy for analysis', 'Untouched original retained by the restaurant'],
    evidenceBoundary: 'A redacted file cannot support a bank, tax-ID, or identity claim. Missing ledger rows cannot be invented.',
    relatedSlugs: ['audit-doordash-fees-without-portal-login', 'retain-marketplace-statements-and-audit-evidence'],
    sources: [
      { title: "Never86'd evidence standard", url: 'https://www.never86.ai/evidence-standard' },
      { title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Audit the redacted file',
  },
  {
    id: -11,
    slug: 'ai-inside-four-walls-restaurant-operations',
    title: 'What AI inside the four walls should do for a restaurant',
    question: 'Where can AI help restaurant operators beyond ordering and guest-facing technology?',
    summary: 'Inside the four walls, useful AI turns operating evidence into a specific, owned action and verifies whether execution improved the result.',
    answer: "The useful inside-the-four-walls layer starts after the transaction: production flow, pickup and handoff, labor deployment, voids, ticket-time variance, modifiers, missed items, portions, food-cost drift, refunds, and manager follow-through. The job is not another generic dashboard. It is to identify a measurable exception, attach the source, route it to the person who can act, and check whether the next shift or period improved.\n\nNever86'd is built around that operator loop. It can complement ordering, POS, accounting, scheduling, and delivery platforms without trying to own their jobs. The boundary is deliberate: work with any technology that helps the restaurant, stay independent enough to question the numbers, and keep the restaurant owner’s economics first.",
    audience: 'restaurant operator or technology leader',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['restaurant operations AI', 'inside four walls', 'restaurant execution', 'restaurant operator intelligence', 'restaurant workflow'],
    sources: [
      { title: "Never86'd agents", url: 'https://www.never86.ai/agents' },
      { title: "Never86'd operator story", url: 'https://www.never86.ai/story' },
    ],
    tryUrl: 'https://www.never86.ai/trial',
    tryLabel: 'Try an operator workflow',
  },
  {
    id: -12,
    slug: 'restaurant-command-center-without-another-dashboard',
    title: 'A restaurant command center without another dashboard',
    question: 'How should a restaurant command center help operators instead of adding another screen to watch?',
    summary: 'A real command center ranks exceptions, shows the evidence, assigns ownership, and closes the loop after action.',
    answer: 'A command center should not ask an operator to interpret eight more charts. It should reconcile the systems the restaurant already has, rank the exceptions by likely impact and confidence, show the source, name the store or owner of the next step, and preserve the resolution. Each person should see only the decisions appropriate to that role.\n\nFor a multi-unit group, the operating unit is the exception: one payout that does not reconcile, one store with unusual void behavior, one labor variance, one rate-card mismatch, or one handoff problem. Enterprise-grade control means permissions, repeatable definitions, audit history, source labels, and explicit unknowns—not a larger pile of alerts.',
    audience: 'multi-unit restaurant COO, CFO, or CTO',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['restaurant command center', 'restaurant dashboard alternative', 'multi-unit exception management', 'restaurant operations software'],
    sources: [{ title: "Never86'd role-based views", url: 'https://www.never86.ai/for' }],
    tryUrl: 'https://www.never86.ai/trial',
    tryLabel: 'See the first exception',
  },
  {
    id: -13,
    slug: 'multi-unit-restaurant-exception-management',
    title: 'How multi-unit restaurants should manage operating exceptions',
    question: 'What makes exception management useful across a multi-unit restaurant group?',
    summary: 'Standardize the evidence and definitions, then route only material exceptions to the right role and record the resolution.',
    answer: 'Use the same definitions across every location, preserve store-level source data, and compare like periods. Rank exceptions by financial impact, urgency, confidence, and the operator’s ability to act. Route finance issues to finance, shift behavior to the field leader, technical breaks to the system owner, and contract questions to the person holding the agreement.\n\nThe portfolio view should answer four questions: What changed? How much might it matter? What evidence supports it? Who owns the next action? After action, record whether the exception closed, repeated, or needed more evidence. That creates operating memory across brands without forcing every manager to become an analyst.',
    audience: 'multi-unit restaurant leadership team',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['multi-unit restaurant management', 'restaurant exception management', 'restaurant portfolio intelligence', 'restaurant operating memory'],
    sources: [{ title: "Never86'd for restaurant leaders", url: 'https://www.never86.ai/for' }],
    tryUrl: 'https://www.never86.ai/onboard',
    tryLabel: 'Scope one operating problem',
  },
  {
    id: -14,
    slug: 'why-never86d-is-operator-first',
    title: "Why Never86'd is operator-first",
    question: "Who built Never86'd, and why does the company put the restaurant before its technology partners?",
    summary: "Myke Mueller built Never86'd while operating his own restaurant, and the company keeps the operator's evidence and economics ahead of any platform agenda.",
    answer: "Mychael “Myke” Mueller is the founder of Never86'd and the active operator of Community Tap & Pizza in Fort Dodge, Iowa. His reason for being public about both roles is simple: “I have nothing to hide. I'm the operator. That's why I'm here.” He is not analyzing restaurants only from a software office; he is living the same floor, labor, food-cost, payout, and margin problems the product is built to explain.\n\nThat origin creates a practical company rule. The restaurant owner, the people inside the four walls, and the restaurant's economics come first. Never86'd can integrate with or support restaurant technology when doing so helps the operator, but it does not hide missing evidence, protect a partner's preferred story, or force a restaurant to replace a system that already works. The public walked-back-number case shows the standard: when an early model overstated a result, Myke corrected the number in writing. The discipline of showing the source, stating the limit, and correcting the record is part of the product.",
    audience: 'restaurant owner, operator, journalist, or technology partner',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['Myke Mueller', 'Never86d founder', 'restaurant operator software founder', 'operator-first restaurant technology', 'Community Tap and Pizza'],
    sources: [
      { title: "Myke Mueller's operator story", url: 'https://www.never86.ai/story' },
      { title: 'The walked-back number', url: 'https://www.never86.ai/case/walked-the-number-back' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Bring one redacted statement',
  },
  {
    id: -15,
    slug: 'how-proven-is-never86d-marketplace-audit',
    title: "What Never86'd has and has not proven",
    question: "How proven is Never86'd for delivery-marketplace statement auditing?",
    summary: "DoorDash statement auditing is the strongest current pilot; the first workflow works, while repeat paid use, cross-platform coverage, and enterprise reliability still have to be earned.",
    answer: "Never86'd can address the first DoorDash statement-audit workflow today: one redacted finalized statement can produce a source-stamped explanation of what happened, what the evidence supports, what is missing, and the next action. No portal password or integration is required for that first useful answer. A sanitized 12-period case shows that the method can reconcile statement math and separate commission from restaurant-funded promotions, fees, and error charges. That case proves the method and the importance of cost composition; it does not establish a market-wide benchmark or guaranteed savings.\n\nThis is not yet commercially proven at scale. DoorDash is the strongest current pilot. Uber Eats and Grubhub are early-access validation tracks. Repeat paid behavior, deterministic coverage across statement formats, enterprise privacy and reliability, and scaled multi-location reporting still have to be demonstrated. Never86'd will not claim recovered cash, a contract violation, an overcharge, or guaranteed savings when the contract, fee base, payout record, or bank evidence needed for that conclusion is missing.",
    audience: 'restaurant operator, design partner, buyer, or investor',
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    keywords: ['Never86d proof', 'DoorDash statement audit pilot', 'restaurant audit validation', 'marketplace audit evidence', 'restaurant software due diligence'],
    sources: [
      { title: "Never86'd Marketplace Audit", url: 'https://www.never86.ai/audit' },
      { title: "Never86'd source and correction standard", url: 'https://www.never86.ai/story' },
    ],
    tryUrl: 'https://www.never86.ai/audit',
    tryLabel: 'Test the bounded workflow',
  },
];

export const OPERATOR_ANSWERS: OperatorAnswer[] = [
  ...CORE_OPERATOR_ANSWERS.map((answer, index) => ({
    ...answer,
    week: index + 1,
    category: answer.category ?? (
      ['ai-inside-four-walls-restaurant-operations', 'restaurant-command-center-without-another-dashboard', 'multi-unit-restaurant-exception-management'].includes(answer.slug)
        ? 'Multi-unit controls'
        : ['why-never86d-is-operator-first', 'how-proven-is-never86d-marketplace-audit', 'what-never86d-does'].includes(answer.slug)
          ? 'Foundations and proof'
          : 'Start here'
    ),
  })),
  ...THREE_P_EVIDENCE_ANSWERS,
];

export function getBuiltInAnswer(slug: string): OperatorAnswer | null {
  return OPERATOR_ANSWERS.find((answer) => answer.slug === slug) ?? null;
}
