import type { OperatorAnswer } from './operatorAnswers';

const AUTHOR = 'Mychael “Myke” Mueller';
const PUBLISHED_AT = '2026-08-21T00:30:00-05:00';
const UPDATED_AT = '2026-08-21T00:30:00-05:00';
const AUDIT = 'https://www.never86.ai/audit';
const DD_STATEMENT = 'https://help.doordash.com/merchants/s/article/MX-Monthly-Statement-and-FAQs?language=en_US';
const DD_FINANCIALS = 'https://help.doordash.com/en-us/merchants/article/how-can-i-receive-my-weekly-pay-statements';
const DD_ERRORS = 'https://help.doordash.com/en-ca/merchants/article/what-are-order-error-adjustments';
const DD_TAX = 'https://help.doordash.com/en-us/merchants/article/merchant-tax-facilitator-us';
const DD_DELAY = 'https://help.doordash.com/en-us/merchants/article/prevent-payment-delays';
const UBER_REPORTS = 'https://merchants.ubereats.com/us/en/faq/';
const UBER_SALES = 'https://merchants.ubereats.com/us/en/faq/';
const UBER_ERRORS = 'https://merchants.ubereats.com/us/en/academy/order-errors/';
const GH_STATEMENT = 'https://get.grubhub.com/help-center/grubhub-finacial-statement/';

type Draft = Omit<OperatorAnswer, 'author' | 'publishedAt' | 'updatedAt' | 'tryUrl' | 'tryLabel'>;

function guide(draft: Draft): OperatorAnswer {
  return {
    ...draft,
    author: AUTHOR,
    publishedAt: PUBLISHED_AT,
    updatedAt: UPDATED_AT,
    tryUrl: AUDIT,
    tryLabel: 'Run it on one redacted statement',
  };
}

export const THREE_P_EVIDENCE_ANSWERS: OperatorAnswer[] = [
  guide({
    id: -16,
    week: 16,
    category: 'DoorDash statements',
    slug: 'doordash-estimated-transactions-vs-finalized-payouts',
    title: 'DoorDash estimated transactions versus finalized payouts',
    question: 'Should a restaurant reconcile DoorDash from the Transactions screen or the finalized Payouts data?',
    summary: 'Use finalized payout data for financial reconciliation; estimated transaction views are useful for operations but can still change.',
    answer: 'DoorDash describes the Transactions view as an estimate and the Payouts view as finalized payment data with the order-level detail included in the settlement. For a weekly close, start with the finalized payout ID and its included transactions. Keep the estimated view only as an operating cross-check.\n\nIf an operator compares an estimated transaction total with a later bank deposit, timing and post-order amendments can look like a shortage even when the finalized payout is internally correct. Anchor the bridge to the payout record, then test the deposit and contract separately.',
    audience: 'restaurant owner, bookkeeper, or controller',
    keywords: ['DoorDash finalized payout', 'DoorDash Transactions estimate', 'DoorDash reconciliation', 'restaurant payout data'],
    formula: 'Finalized sales − commission and fees − marketing spend + amendments = expected net payout',
    fieldChecks: ['Record the payout ID and covered dates.', 'Export the finalized order-level rows included in that payout.', 'Compare expected net payout with the matching bank deposit.'],
    evidenceNeeded: ['Finalized payout export', 'Included transaction detail', 'Matching bank deposit'],
    evidenceBoundary: 'An estimated screen cannot prove a missing payment. Use the finalized payout record before opening a variance.',
    relatedSlugs: ['reconcile-doordash-payout-to-bank-deposit', 'doordash-monthly-statement-vs-payout-period'],
    sources: [{ title: 'DoorDash: Financials, payouts, and statements', url: DD_FINANCIALS }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -17,
    week: 17,
    category: 'DoorDash statements',
    slug: 'doordash-monthly-statement-vs-payout-period',
    title: 'DoorDash monthly statements versus payout periods',
    question: 'Why can a DoorDash monthly statement differ from the payouts deposited during that same calendar month?',
    summary: 'Monthly statements follow transaction dates, while payouts can cover settlement periods that cross month-end.',
    answer: 'DoorDash states that a monthly statement contains transactions completed in the calendar month, while a payout contains the transactions included in its settlement period. Those periods can straddle two months. That means the sum of deposits dated in August does not automatically equal the August monthly statement.\n\nBuild two schedules: a calendar-month activity schedule for accounting and a payout-to-bank schedule for cash. Connect them with transaction or payout IDs. Never plug the difference into fees; carry it as a timing bridge until each transaction is assigned to a finalized payout.',
    audience: 'restaurant accountant, controller, or owner',
    keywords: ['DoorDash monthly statement', 'DoorDash payout period', 'month end reconciliation', 'restaurant cash timing'],
    formula: 'Calendar-month activity ± settlement timing = payouts assigned to deposits',
    fieldChecks: ['List transactions by completion date.', 'List finalized payouts by payout ID and covered period.', 'Carry cross-month transactions as timing items, not unexplained expense.'],
    evidenceNeeded: ['Monthly statement', 'Finalized payout exports', 'Bank activity for both adjacent months'],
    evidenceBoundary: 'A calendar-month difference is not evidence of an incorrect fee until settlement timing has been bridged.',
    relatedSlugs: ['marketplace-payouts-that-cross-month-end', 'third-party-delivery-month-end-close-checklist'],
    sources: [{ title: 'DoorDash: Payout and monthly statement definitions', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -18,
    week: 18,
    category: 'DoorDash statements',
    slug: 'understand-doordash-amendments-and-adjustments',
    title: 'How to understand DoorDash amendments and adjustments',
    question: 'What should a restaurant do with DoorDash amendments and adjustments on a financial statement?',
    summary: 'Treat amendments as a separate ledger that can contain both error charges and later corrections; trace each material row to an order or prior period.',
    answer: 'DoorDash groups error charges and other adjustments under amendments. An amendment can reduce or increase earnings, so the net line alone is not enough. Export the underlying rows, preserve the sign, transaction date, order reference, reason, and the payout where the amendment settled.\n\nFor recurring close work, separate original-period economics from later-period corrections. A credit received this week for a prior error charge should close the earlier exception, not make the current week look unusually profitable. Material unexplained rows remain open until the platform detail supports the label.',
    audience: 'restaurant finance lead or owner',
    keywords: ['DoorDash amendments', 'DoorDash adjustments', 'restaurant statement corrections', 'payout ledger'],
    formula: 'Expected payout = sales − fees − marketing spend + signed amendments',
    fieldChecks: ['Split positive and negative amendments.', 'Trace material rows to an order, reason, and original period.', 'Link later credits back to the original exception.'],
    evidenceNeeded: ['Amendment detail', 'Order reference', 'Original and settlement-period payouts'],
    evidenceBoundary: 'An amendment label alone does not prove the charge was valid or invalid; the order and policy context are still required.',
    relatedSlugs: ['review-doordash-error-charges', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'DoorDash: Financial terminology and net-total math', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -19,
    week: 19,
    category: 'Refunds and error charges',
    slug: 'review-doordash-error-charges',
    title: 'How to review DoorDash error charges without guessing',
    question: 'How can a restaurant determine which DoorDash error charges deserve review?',
    summary: 'Start with order-level evidence, reason codes, and repeat patterns; do not label the full error-charge total invalid.',
    answer: 'DoorDash describes error charges as amounts related to customer reimbursements for missing or incorrect items. Review them at the order and item level. Rank by dollar value, repeated item, store, shift, reason, and whether restaurant-held evidence contradicts the charge.\n\nThe practical split is operational versus disputable. A repeated missing-item pattern may be a real execution issue even when the charge is correctly applied. A specific order with packing proof or contradictory platform detail may deserve a dispute. Keep the platform decision and any later credit tied to the original order.',
    audience: 'restaurant operator, finance lead, or field leader',
    keywords: ['DoorDash error charges', 'DoorDash refund dispute', 'missing item charges', 'restaurant order errors'],
    fieldChecks: ['Export order-level error-charge detail.', 'Rank repeat reasons by store, item, and shift.', 'Attach available packing, ticket, or handoff evidence before disputing.'],
    evidenceNeeded: ['Order and item detail', 'Error reason', 'Restaurant-held fulfillment evidence'],
    evidenceBoundary: 'The presence of an error charge is not proof of an overcharge. A defensible dispute needs order-specific contradictory evidence.',
    relatedSlugs: ['understand-doordash-amendments-and-adjustments', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'DoorDash: Understanding error charges and disputes', url: DD_ERRORS }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -20,
    week: 20,
    category: 'Promotions and marketing',
    slug: 'doordash-funded-vs-restaurant-funded-promotions',
    title: 'DoorDash-funded versus restaurant-funded promotions',
    question: 'How should a restaurant separate its own promotional funding from discounts funded by DoorDash or another party?',
    summary: 'Attribute only the restaurant-funded share to the restaurant and preserve marketplace or third-party credits as separate offsets.',
    answer: 'A promotion can have more than one funder. DoorDash reporting separates customer discounts funded by the restaurant, DoorDash, or a third party, and it can also show credits that offset marketing costs. Record those components separately before calculating restaurant-borne channel cost.\n\nIf the restaurant funds $300 and DoorDash funds $200, the operator should not call the full $500 a restaurant cost. The campaign may still affect order mix and margin, but the funding ledger must be correct before anyone evaluates performance or assigns an owner.',
    audience: 'restaurant marketer, owner, or finance lead',
    keywords: ['DoorDash funded promotion', 'restaurant funded discount', 'DoorDash marketing credit', 'delivery promotion accounting'],
    formula: 'Restaurant-borne promotion cost = restaurant-funded discounts + marketing fees − applicable platform or third-party credits',
    fieldChecks: ['Separate each promotion by funding party.', 'Tie credits to the campaign and statement period.', 'Measure sales and contribution only after the funding split is correct.'],
    evidenceNeeded: ['Promotion detail', 'Funding-party fields', 'Marketing credits and campaign dates'],
    evidenceBoundary: 'A discount shown to the guest is not automatically a restaurant-funded expense.',
    relatedSlugs: ['restaurant-funded-promotions-delivery-statement', 'measure-delivery-promotion-roi'],
    sources: [{ title: 'DoorDash: Marketing-spend terminology', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -21,
    week: 21,
    category: 'Promotions and marketing',
    slug: 'audit-doordash-marketing-spend',
    title: 'How to audit DoorDash marketing spend',
    question: 'What should a restaurant compare before deciding whether DoorDash ads or promotions worked?',
    summary: 'Separate marketing fees, restaurant-funded discounts, credits, and incremental contribution instead of judging a campaign from sales alone.',
    answer: 'DoorDash reporting can include marketing fees, restaurant-funded customer discounts, platform-funded discounts, third-party contributions, and credits. Reconcile those components first. Then compare the campaign period with a reasonable baseline using the same stores, hours, menu availability, and eligible-sales definition.\n\nSales lift is not profit. Estimate incremental contribution only after subtracting marketplace fees, restaurant-funded incentives, food and packaging cost, and any incremental labor. If the baseline is weak or the campaign overlaps another change, label the ROI directional instead of precise.',
    audience: 'restaurant marketer, CFO, or owner',
    keywords: ['DoorDash marketing spend', 'DoorDash ads ROI', 'delivery promotion audit', 'restaurant campaign profitability'],
    formula: 'Estimated campaign contribution = incremental eligible sales − incremental marketplace cost − restaurant-funded incentives − incremental food, packaging, and labor',
    fieldChecks: ['Reconcile every campaign charge and credit.', 'Choose a comparable baseline period.', 'Separate sales lift from estimated contribution.'],
    evidenceNeeded: ['Campaign dates and stores', 'Marketing charges, discounts, and credits', 'Comparable sales and cost inputs'],
    evidenceBoundary: 'A statement proves observed campaign cost, not incremental demand. Causal ROI needs a credible comparison.',
    relatedSlugs: ['doordash-funded-vs-restaurant-funded-promotions', 'measure-delivery-promotion-roi'],
    sources: [{ title: 'DoorDash: Marketing-spend definitions', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -22,
    week: 22,
    category: 'Taxes and pass-throughs',
    slug: 'doordash-marketplace-facilitator-tax-lines',
    title: 'How to read DoorDash marketplace-facilitator tax lines',
    question: 'Why should marketplace-facilitator taxes be separated from restaurant revenue and marketplace fees?',
    summary: 'Identify who collected and remitted each tax before treating it as restaurant revenue, expense, or cash owed.',
    answer: 'Marketplace-facilitator rules can make the platform responsible for collecting and remitting certain taxes. DoorDash says merchants can view remitted tax in payout and monthly-statement reporting and download a subtotal tax breakdown with jurisdiction, taxable basis, amount, and remittance responsibility.\n\nFor reconciliation, keep customer tax, tax passed to the restaurant, tax remitted by the marketplace, and tax applied to marketplace fees in separate columns. This prevents a pass-through tax from distorting gross sales, channel cost, or the expected deposit. Tax treatment varies by jurisdiction, so the schedule should be reviewed with the restaurant’s accountant.',
    audience: 'restaurant accountant, controller, or owner',
    keywords: ['DoorDash marketplace facilitator tax', 'restaurant delivery tax', 'DoorDash tax statement', 'marketplace tax reconciliation'],
    fieldChecks: ['Download the jurisdiction-level tax breakdown.', 'Record the named remittance party for each tax.', 'Keep fee tax separate from order-subtotal tax.'],
    evidenceNeeded: ['Monthly subtotal tax breakdown', 'Payout or monthly statement', 'Restaurant chart of accounts and jurisdiction guidance'],
    evidenceBoundary: 'Never86’d can organize the evidence and math but does not determine a restaurant’s tax filing position.',
    relatedSlugs: ['separate-tips-taxes-and-pass-through-amounts', 'third-party-delivery-month-end-close-checklist'],
    sources: [{ title: 'DoorDash: US marketplace facilitator FAQ', url: DD_TAX }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -23,
    week: 23,
    category: 'Refunds and error charges',
    slug: 'reconcile-cancelled-doordash-orders',
    title: 'How to reconcile cancelled DoorDash orders',
    question: 'How should a restaurant test whether a cancelled DoorDash order was paid or reversed correctly?',
    summary: 'Trace the order status, preparation or pickup event, payout treatment, and any later amendment instead of applying one rule to every cancellation.',
    answer: 'Cancelled orders can have different payment treatment depending on when cancellation occurred and what happened operationally. Start with the final order status, cancellation reason, acceptance and preparation timing, pickup evidence when available, and the payout or amendment where the order settled.\n\nKeep paid cancellations, unpaid cancellations, and later reversals separate. An order showing sales in one export may be corrected in a later payout. The operator’s job is to build the complete order timeline and compare it with the marketplace’s current merchant policy before escalating.',
    audience: 'restaurant operator or finance lead',
    keywords: ['DoorDash cancelled order payout', 'DoorDash cancellation reconciliation', 'restaurant cancelled delivery order'],
    fieldChecks: ['Export cancelled-order status and reason.', 'Capture preparation, pickup, and support evidence.', 'Trace the original transaction and any later amendment.'],
    evidenceNeeded: ['Order timeline', 'Cancellation reason', 'Payout and amendment history'],
    evidenceBoundary: 'A cancelled status alone does not establish whether payment was owed; policy and order events matter.',
    relatedSlugs: ['understand-doordash-amendments-and-adjustments', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'DoorDash: Payout and statement terminology', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -24,
    week: 24,
    category: 'Payout reconciliation',
    slug: 'investigate-missing-or-delayed-doordash-payout',
    title: 'How to investigate a missing or delayed DoorDash payout',
    question: 'What should a restaurant check before concluding that a DoorDash payout is missing?',
    summary: 'Verify payout status, bank details, business verification, settlement timing, and deposit grouping before calling the amount unpaid.',
    answer: 'Start with the finalized payout record: payout ID, status, amount, scheduled date, and included transactions. Confirm the bank account ending digits and look for verification or account-information notices. DoorDash notes that mismatched business or identity information can delay payment in some situations.\n\nThen search the bank by amount and date range, allowing for processing timing and combined deposits. If the payout shows completed but no matching bank activity exists, preserve screenshots or exports and open a support case with the exact payout ID. Do not email full bank credentials.',
    audience: 'restaurant owner or controller',
    keywords: ['DoorDash missing payout', 'DoorDash delayed payment', 'restaurant payout not received', 'DoorDash bank deposit'],
    fieldChecks: ['Confirm payout status and ID.', 'Verify masked bank destination and account notices.', 'Search adjacent dates and combined deposits before escalating.'],
    evidenceNeeded: ['Finalized payout record', 'Masked bank-account destination', 'Redacted bank activity'],
    evidenceBoundary: 'A late-looking deposit is not a proven missing payout until status, timing, and deposit grouping are checked.',
    relatedSlugs: ['reconcile-doordash-payout-to-bank-deposit', 'match-one-marketplace-payout-to-multiple-bank-deposits'],
    sources: [{ title: 'DoorDash: Preventing payment delays', url: DD_DELAY }, { title: 'DoorDash: Finalized payout data', url: DD_FINANCIALS }],
  }),
  guide({
    id: -25,
    week: 25,
    category: 'Multi-unit controls',
    slug: 'reconcile-doordash-across-multiple-locations',
    title: 'How to reconcile DoorDash across multiple restaurant locations',
    question: 'What control prevents multi-location DoorDash statements and deposits from becoming one unexplained net number?',
    summary: 'Maintain a location-to-store-to-payout map and reconcile at the lowest available level before rolling up the group.',
    answer: 'Create a permanent map between legal entity, bank account, restaurant location, marketplace store ID, POS location, and accounting location. Reconcile each finalized payout to that map before rolling totals into a brand or portfolio view. Preserve shared campaigns or brand-funded promotions as separate allocations.\n\nA group total can tie while one store is missing and another is duplicated. Require store counts, payout counts, and exception counts alongside dollars. When deposits combine locations, keep the payout-level bridge that explains exactly how the bank amount was assembled.',
    audience: 'multi-unit restaurant controller, CFO, or operator',
    keywords: ['multi-location DoorDash reconciliation', 'restaurant store ID mapping', 'multi-unit payout control', 'DoorDash portfolio reporting'],
    fieldChecks: ['Maintain the entity-location-store-ID map.', 'Reconcile each payout before portfolio rollup.', 'Test store and payout counts as well as dollars.'],
    evidenceNeeded: ['Marketplace store IDs', 'POS and accounting location IDs', 'Payout-to-bank mapping'],
    evidenceBoundary: 'A group-level tie does not prove every location is complete and unique.',
    relatedSlugs: ['multi-unit-restaurant-exception-management', 'find-duplicate-or-missing-marketplace-settlements'],
    sources: [{ title: 'DoorDash: Payout-level order detail', url: DD_FINANCIALS }, { title: "Never86'd multi-unit exception model", url: 'https://www.never86.ai/answers/multi-unit-restaurant-exception-management' }],
  }),
  guide({
    id: -26,
    week: 26,
    category: 'Uber Eats statements',
    slug: 'understand-uber-eats-payment-details-report',
    title: 'How to understand the Uber Eats Payment Details report',
    question: 'Which Uber Eats report should a restaurant use to explain sales, taxes, service fees, adjustments, and payout?',
    summary: 'Use the Payment Details report for the financial bridge and pair it with operational reports when a refund or order issue needs explanation.',
    answer: 'Uber provides past payment statements and order-by-order breakdowns with order number, date, time, tax, subtotal, fees, adjustments, and net payout. Use the Payment Details export as the financial base, then bring in the Order Errors report when an adjustment needs item-level operating context.\n\nRequest the correct stores and date range, preserve the raw file, and document the report generation time. A screen can summarize amounts owed, but the exported report provides a more reproducible audit trail. Keep marketplace cost, expected payout, and actual deposit as separate tests.',
    audience: 'restaurant owner, controller, or accountant',
    keywords: ['Uber Eats Payment Details report', 'Uber Eats financial report', 'Uber Eats payout reconciliation', 'restaurant Uber reports'],
    fieldChecks: ['Request Payment Details for the exact period and stores.', 'Pair material adjustments with transaction-level error or order history.', 'Preserve the original export and report request date.'],
    evidenceNeeded: ['Payment Details report', 'Relevant operational report', 'Matching payout or bank record'],
    evidenceBoundary: 'A payment report can explain observed economics; contract compliance still requires the governing agreement.',
    relatedSlugs: ['download-uber-eats-reports-for-audit', 'reconcile-uber-eats-payout-to-bank'],
    sources: [{ title: 'Uber Eats Manager: Reports page and report types', url: UBER_REPORTS }, { title: 'Uber Eats Manager: Sales and payment detail', url: UBER_SALES }],
  }),
  guide({
    id: -27,
    week: 27,
    category: 'Refunds and error charges',
    slug: 'review-uber-eats-order-error-adjustments',
    title: 'How to review Uber Eats order error adjustments',
    question: 'What evidence should a restaurant collect before challenging an Uber Eats order error adjustment?',
    summary: 'Match the weekly statement adjustment to the transaction, items, reason, and restaurant-held fulfillment evidence.',
    answer: 'Uber states that customer refunds tied to order mistakes appear as Order Error Adjustments on the weekly payment statement. Pull the transaction-level order-error report, identify the affected item and reason, and compare it with the ticket, packing process, handoff record, or other evidence the restaurant actually retains.\n\nSeparate two outcomes: an operational pattern to fix and a specific adjustment to question. Track support submissions, decision dates, and later credits. Do not call every refund invalid, and do not erase a real store-level pattern because a few disputes were approved.',
    audience: 'restaurant operator, finance lead, or field leader',
    keywords: ['Uber Eats order error adjustment', 'Uber Eats refund dispute', 'restaurant order errors', 'Uber weekly statement'],
    fieldChecks: ['Tie the adjustment to the order and item.', 'Compare the stated reason with restaurant-held evidence.', 'Track the support decision and any later payout credit.'],
    evidenceNeeded: ['Weekly payment statement', 'Order Errors Transaction report', 'Restaurant fulfillment evidence'],
    evidenceBoundary: 'An adjustment is an observed deduction, not automatic proof that the marketplace or restaurant was wrong.',
    relatedSlugs: ['understand-uber-eats-payment-details-report', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'Uber: Issues with weekly pay statements', url: UBER_ERRORS }, { title: 'Uber Eats Manager report types', url: UBER_REPORTS }],
  }),
  guide({
    id: -28,
    week: 28,
    category: 'Uber Eats statements',
    slug: 'download-uber-eats-reports-for-audit',
    title: 'Which Uber Eats reports to download for an audit',
    question: 'What should a restaurant export from Uber Eats Manager before investigating a payout, refund, or performance issue?',
    summary: 'Request Payment Details, Order Errors Transaction, and Order History for the same stores and period; add item-level reports only when needed.',
    answer: 'Start with the past payment statement or Payment Details export for financial activity and the Order Errors report for refund and adjustment transparency. Add available order-level detail when status or timing matters. Choose the smallest set that answers the question and keep every file on the same date range and store scope.\n\nPreserve the raw exports internally when requested so a later question can be reproduced without rebuilding the evidence from screenshots. Record the export date, selected locations, and covered period in a simple manifest.',
    audience: 'restaurant owner, analyst, or finance team',
    keywords: ['download Uber Eats reports', 'Uber Reports Hub', 'Uber payment details CSV', 'Uber order history'],
    fieldChecks: ['Define the question before selecting reports.', 'Use identical store and date filters.', 'Archive the raw exports with a manifest.'],
    evidenceNeeded: ['Payment Details or payment statement', 'Order Errors report', 'Order-level detail when timing or status matters'],
    evidenceBoundary: 'More files do not create certainty if their store scope or date definitions differ.',
    relatedSlugs: ['understand-uber-eats-payment-details-report', 'review-uber-eats-order-error-adjustments'],
    sources: [{ title: 'Uber Eats Manager: Reports page', url: UBER_REPORTS }, { title: "Never86'd redaction guide", url: 'https://www.never86.ai/answers/what-to-redact-from-restaurant-statement-before-ai-audit' }],
  }),
  guide({
    id: -29,
    week: 29,
    category: 'Payout reconciliation',
    slug: 'reconcile-uber-eats-payout-to-bank',
    title: 'How to reconcile an Uber Eats payout to the bank',
    question: 'How should a restaurant bridge Uber Eats sales and deductions to the amount deposited?',
    summary: 'Use payment detail to calculate the amount owed, then match the specific payment period to bank activity and preserve timing differences.',
    answer: 'Start with the Uber payment period and completed orders, then identify taxes, service fees, other charges, order-error adjustments, and any other payment adjustments. Calculate the amount owed to the restaurant and tie it to the payment date shown in Uber Eats Manager. Search the bank by amount, date, and available reference.\n\nIf one deposit covers multiple stores or statements, build a payout-to-deposit bridge rather than forcing each statement to match the bank individually. A matching deposit supports cash reconciliation; it does not independently prove the service-fee rate or refund decision was correct.',
    audience: 'restaurant accountant, controller, or owner',
    keywords: ['Uber Eats payout bank reconciliation', 'Uber deposit mismatch', 'Uber amount owed restaurant', 'restaurant settlement'],
    formula: 'Uber sales and tax components − service fees − order-error adjustments ± other payments = expected amount owed',
    fieldChecks: ['Record the payment period and payment date.', 'Recalculate amount owed from report components.', 'Match or bridge the result to bank activity.'],
    evidenceNeeded: ['Payment Details report', 'Payment date and identifier', 'Redacted bank activity'],
    evidenceBoundary: 'Cash reconciliation and contract-rate testing are separate controls.',
    relatedSlugs: ['understand-uber-eats-payment-details-report', 'match-one-marketplace-payout-to-multiple-bank-deposits'],
    sources: [{ title: 'Uber Eats Manager: Sales tab and amount owed', url: UBER_SALES }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -30,
    week: 30,
    category: 'Promotions and marketing',
    slug: 'audit-uber-eats-promotions-and-credits',
    title: 'How to audit Uber Eats promotions and credits',
    question: 'How can a restaurant tell what it actually funded in an Uber Eats promotion?',
    summary: 'Trace campaign charges and credits in payment detail, then compare the funded amount with the campaign scope and resulting contribution.',
    answer: 'Pull the Payment Details report for the campaign period and locations, then isolate promotion-related deductions, credits, and any service fees tied to the offer. Compare the statement treatment with the campaign setup or agreement retained by the restaurant. Keep platform-funded and restaurant-funded amounts separate.\n\nOnly after the funding ledger reconciles should the team evaluate performance. Compare a defined baseline and use contribution, not gross sales, when possible. If the statement lacks the campaign attribution required to connect costs with orders, record the ROI as unresolved.',
    audience: 'restaurant marketer, owner, or finance lead',
    keywords: ['Uber Eats promotion audit', 'Uber Eats marketing credit', 'restaurant funded discount', 'delivery campaign ROI'],
    fieldChecks: ['Export the campaign-period payment detail.', 'Match deductions and credits to campaign terms.', 'Measure contribution against a documented baseline.'],
    evidenceNeeded: ['Campaign setup or agreement', 'Payment Details report', 'Comparable sales and cost data'],
    evidenceBoundary: 'Observed promotional deductions do not by themselves prove incremental sales or profitable return.',
    relatedSlugs: ['measure-delivery-promotion-roi', 'compare-doordash-uber-eats-grubhub-like-for-like'],
    sources: [{ title: 'Uber Eats Manager: Payment Details report', url: UBER_REPORTS }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -31,
    week: 31,
    category: 'Refunds and error charges',
    slug: 'reconcile-cancelled-uber-eats-orders',
    title: 'How to reconcile cancelled Uber Eats orders',
    question: 'What should a restaurant examine when an Uber Eats cancellation and payout treatment do not make sense?',
    summary: 'Build the order timeline, compare the payment-statement treatment, and check for later reversals or adjustments.',
    answer: 'Use available order-level detail to establish acceptance, cancellation, fulfillment, pickup, and final status. Then trace the order through the payment statement and any later adjustment. Some cancellations can create a transaction in one period and a reversal in another, so a single report window can show only half the event.\n\nDocument the current merchant policy applicable to the order type and market, and keep support outcomes tied to the order ID. The defensible conclusion is the observed statement treatment and whether it matches the available policy and event evidence—not a blanket rule for all cancelled orders.',
    audience: 'restaurant operator or finance lead',
    keywords: ['Uber Eats cancelled order payout', 'Uber cancellation adjustment', 'restaurant payment statement', 'Uber order history'],
    fieldChecks: ['Export the full order timeline.', 'Trace both original payment and later reversal.', 'Compare with the applicable policy before escalating.'],
    evidenceNeeded: ['Order-level status detail', 'Payment statement or Payment Details export', 'Applicable policy and support record'],
    evidenceBoundary: 'Cancellation treatment depends on order events and policy; the status label alone is insufficient.',
    relatedSlugs: ['download-uber-eats-reports-for-audit', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'Uber Eats Manager: Order History and Payment Details', url: UBER_REPORTS }, { title: 'Uber: Weekly statement issues', url: UBER_ERRORS }],
  }),
  guide({
    id: -32,
    week: 32,
    category: 'Grubhub and catering',
    slug: 'understand-grubhub-restaurant-financial-statement',
    title: 'How to understand a Grubhub restaurant financial statement',
    question: 'Which sections of a Grubhub statement matter when explaining revenue, promotions, adjustments, and payment?',
    summary: 'Separate marketplace orders, cancelled orders, prepaid orders, promotions, and order adjustments before reconciling the payment.',
    answer: 'Grubhub describes its restaurant financial statement as including marketplace orders, cancelled orders, prepaid orders, promotions, and order adjustments. Treat each section as a separate ledger before calculating what the restaurant kept. In particular, prepaid orders can include more than one channel type, while order adjustments can reflect refunds or upcharges after an order.\n\nReconcile the statement total to the payment and bank deposit, then test individual fee or contract questions separately. Preserve store, period, order, and payment references so later credits or corrections can be linked back to the original event.',
    audience: 'restaurant owner, bookkeeper, or controller',
    keywords: ['Grubhub financial statement', 'Grubhub restaurant payout', 'Grubhub marketplace orders', 'Grubhub payment reconciliation'],
    fieldChecks: ['Separate each statement section.', 'Trace material adjustments to orders.', 'Match the resulting payment with the bank.'],
    evidenceNeeded: ['Grubhub financial statement', 'Order or adjustment detail', 'Matching bank deposit'],
    evidenceBoundary: 'A statement can explain observed payment math; a contract-rate conclusion requires the governing agreement.',
    relatedSlugs: ['review-grubhub-order-adjustments', 'reconcile-grubhub-payment-to-bank'],
    sources: [{ title: 'Grubhub: Understanding the restaurant financial statement', url: GH_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -33,
    week: 33,
    category: 'Refunds and error charges',
    slug: 'review-grubhub-order-adjustments',
    title: 'How to review Grubhub order adjustments',
    question: 'What should a restaurant do with refunds and upcharges shown in the Grubhub order-adjustments section?',
    summary: 'Trace every material adjustment to its order, reason, direction, and settlement period, then separate operational fixes from payment questions.',
    answer: 'Grubhub says its order-adjustments section can contain customer refunds and upcharges applied after the order. Split positive and negative adjustments, then tie each material row to the order, reason, and statement period where it settled. Compare with restaurant-held ticket or handoff evidence when available.\n\nA pattern of adjustments may point to an operating issue even when individual amounts are correct. Conversely, one well-documented order may deserve support review. Track later credits or reversals back to the originating order so the resolution closes the original exception.',
    audience: 'restaurant operator or finance lead',
    keywords: ['Grubhub order adjustments', 'Grubhub refunds', 'Grubhub upcharges', 'restaurant order reconciliation'],
    fieldChecks: ['Split positive and negative adjustments.', 'Tie material rows to orders and reasons.', 'Track any later correction to the original exception.'],
    evidenceNeeded: ['Statement adjustment section', 'Order detail', 'Restaurant fulfillment or support evidence'],
    evidenceBoundary: 'An adjustment is a financial event; determining fault requires order-specific evidence.',
    relatedSlugs: ['understand-grubhub-restaurant-financial-statement', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'Grubhub: Order adjustments on financial statements', url: GH_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -34,
    week: 34,
    category: 'Grubhub and catering',
    slug: 'grubhub-marketplace-cancelled-and-prepaid-orders',
    title: 'Grubhub marketplace, cancelled, and prepaid orders',
    question: 'Why should Grubhub marketplace orders, cancelled orders, and prepaid orders be kept separate?',
    summary: 'The sections represent different order and payment paths; combining them can hide cancellation treatment or channel mix.',
    answer: 'Grubhub’s statement guidance separates marketplace orders, cancelled orders, and prepaid orders. Prepaid orders can include activity from the restaurant’s Grubhub page, phone orders, partner channels, and branded channels. Those sources may not share the same economics or operating owner.\n\nBuild a section-level bridge before calculating a blended rate. Confirm which orders generated marketplace fees, which were cancelled, and which originated through another prepaid channel. If the detail needed to allocate a deduction is missing, keep it unassigned instead of spreading it across all sales.',
    audience: 'restaurant owner, accountant, or channel manager',
    keywords: ['Grubhub prepaid orders', 'Grubhub marketplace orders', 'Grubhub cancelled orders', 'restaurant channel mix'],
    fieldChecks: ['Preserve the statement sections.', 'Map prepaid channels separately.', 'Allocate deductions only when the evidence supports the base.'],
    evidenceNeeded: ['Statement sections', 'Order-source detail', 'Applicable fee or channel terms'],
    evidenceBoundary: 'A blended net amount cannot explain which channel or order type created the cost.',
    relatedSlugs: ['understand-grubhub-restaurant-financial-statement', 'calculate-profit-by-delivery-platform'],
    sources: [{ title: 'Grubhub: Statement section definitions', url: GH_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -35,
    week: 35,
    category: 'Payout reconciliation',
    slug: 'reconcile-grubhub-payment-to-bank',
    title: 'How to reconcile a Grubhub payment to the bank',
    question: 'What is the cleanest way to match a Grubhub financial statement with the restaurant’s deposit?',
    summary: 'Calculate the payment from statement sections and adjustments, then match the payment reference, date, and amount to bank activity.',
    answer: 'Start with the statement associated with the payment, separate marketplace, prepaid, cancelled, promotional, and adjustment activity, and calculate the net amount expected to be paid. Record the payment period and any available reference. Match that amount with a redacted bank transaction.\n\nIf one deposit combines stores or more than one statement, build a bridge listing every component. If the dates or amounts do not match, search adjacent processing dates and later adjustment periods before creating an exception. Preserve the difference rather than forcing it into a generic fee account.',
    audience: 'restaurant bookkeeper, controller, or owner',
    keywords: ['Grubhub bank reconciliation', 'Grubhub restaurant deposit', 'Grubhub payment statement', 'restaurant payout'],
    fieldChecks: ['Recalculate the statement payment.', 'Record payment date and reference.', 'Match or bridge the amount to bank activity.'],
    evidenceNeeded: ['Grubhub statement', 'Payment reference', 'Redacted bank transaction'],
    evidenceBoundary: 'A matching bank deposit proves cash receipt, not contract compliance or the validity of each adjustment.',
    relatedSlugs: ['understand-grubhub-restaurant-financial-statement', 'match-one-marketplace-payout-to-multiple-bank-deposits'],
    sources: [{ title: 'Grubhub: Financial statement overview', url: GH_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -36,
    week: 36,
    category: 'Grubhub and catering',
    slug: 'audit-ezcater-catering-statement',
    title: 'How to audit an ezCater or catering marketplace statement',
    question: 'What should a restaurant separate when reviewing catering marketplace economics?',
    summary: 'Separate food sales, delivery, tips, commissions, marketing, refunds, credits, and operational fulfillment costs before calculating contribution.',
    answer: 'Catering orders can mix food revenue, delivery charges, tips, marketplace commissions, promotions, refunds, and adjustments. Build the statement bridge first, then add restaurant-held delivery labor, packaging, driver, and food-cost evidence when calculating contribution. Keep gratuity and pass-through delivery amounts out of the commission denominator unless the agreement says otherwise.\n\nNever86’d treats ezCater and other catering statements as an early-access validation track. The first result should explain observed statement math and missing evidence. It should not claim complete platform coverage, recovered cash, or contract noncompliance without the governing documents.',
    audience: 'restaurant catering leader, owner, or finance team',
    keywords: ['ezCater statement audit', 'catering commission', 'catering marketplace fees', 'restaurant catering reconciliation'],
    formula: 'Observed catering channel contribution = eligible food sales − marketplace costs − restaurant-funded promotions − incremental fulfillment costs',
    fieldChecks: ['Separate statement categories and pass-throughs.', 'Add restaurant-held fulfillment costs.', 'Test contract rates only with the applicable agreement.'],
    evidenceNeeded: ['Finalized catering statement', 'Order and fulfillment detail', 'Rate card or agreement when testing rates'],
    evidenceBoundary: 'The workflow is available as early-access validation; it is not represented as proven deterministic coverage at scale.',
    relatedSlugs: ['calculate-true-third-party-delivery-cost', 'calculate-delivery-menu-item-contribution'],
    sources: [{ title: "Never86'd Marketplace Audit", url: AUDIT }, { title: "Never86'd proof boundary", url: 'https://www.never86.ai/answers/how-proven-is-never86d-marketplace-audit' }],
  }),
  guide({
    id: -37,
    week: 37,
    category: 'Close and accounting',
    slug: 'third-party-delivery-month-end-close-checklist',
    title: 'A month-end close checklist for third-party delivery',
    question: 'What should a restaurant close every month for DoorDash, Uber Eats, Grubhub, and catering marketplaces?',
    summary: 'Close completeness, statement math, cash, timing, adjustments, taxes, and open exceptions separately for every platform and location.',
    answer: 'A reliable close begins with completeness: every active store and marketplace, every finalized statement or payout, and every bank account. Recalculate statement math, match payouts to deposits, roll cross-month timing items, classify fees and promotions, trace material refunds or adjustments, and separate marketplace-remitted taxes and tips.\n\nFinish with an exception register showing amount, evidence status, owner, due date, and resolution. The close is not complete because the net number was posted. It is complete when the team can explain the money path and identify what remains open without burying the difference.',
    audience: 'restaurant accountant, controller, CFO, or owner',
    keywords: ['restaurant month end close', 'third party delivery accounting', 'DoorDash Uber Grubhub reconciliation', 'marketplace close checklist'],
    fieldChecks: ['Prove store and statement completeness.', 'Reconcile each platform statement to payout and bank.', 'Carry open exceptions with owner and evidence status.'],
    evidenceNeeded: ['Finalized statements and payouts', 'Bank activity', 'Store-platform map and exception register'],
    evidenceBoundary: 'A posted net deposit is not a complete close if fees, timing, or open differences remain unexplained.',
    relatedSlugs: ['book-third-party-delivery-gross-not-net', 'map-delivery-fees-to-chart-of-accounts'],
    sources: [{ title: 'DoorDash: Finalized reconciliation data', url: DD_FINANCIALS }, { title: 'Uber Eats Manager: Financial and operational reports', url: UBER_REPORTS }, { title: 'Grubhub: Financial statement sections', url: GH_STATEMENT }],
  }),
  guide({
    id: -38,
    week: 38,
    category: 'Close and accounting',
    slug: 'book-third-party-delivery-gross-not-net',
    title: 'Why restaurants should not book only the net delivery deposit',
    question: 'What gets hidden when a restaurant records only the DoorDash, Uber Eats, or Grubhub bank deposit as revenue?',
    summary: 'Net-deposit posting can collapse sales, fees, promotions, refunds, taxes, and adjustments into one number and destroy the audit trail.',
    answer: 'The bank deposit is cash, not the full economic story. A marketplace statement can include gross or eligible sales, commissions, merchant fees, marketing, restaurant-funded discounts, refunds, adjustments, taxes, tips, and credits before arriving at the payout. Recording only the net deposit can understate both revenue and expense and make platform comparisons impossible.\n\nBuild a statement journal that records the relevant gross activity and separately classified deductions, then clears the marketplace receivable when the deposit arrives. The restaurant’s accountant should decide the final entries and tax treatment, but the operational ledger should preserve the categories and source rows.',
    audience: 'restaurant bookkeeper, accountant, or owner',
    keywords: ['book DoorDash gross sales', 'net deposit accounting', 'restaurant marketplace journal entry', 'delivery fee accounting'],
    formula: 'Eligible sales and pass-throughs − classified deductions ± adjustments = marketplace receivable cleared by payout',
    fieldChecks: ['Preserve gross statement categories.', 'Post deductions to named accounts, not net sales.', 'Clear the receivable with the matched deposit.'],
    evidenceNeeded: ['Finalized statement', 'Chart of accounts', 'Bank deposit and accountant-approved policy'],
    evidenceBoundary: 'Never86’d supplies a reconciliation schedule, not tax or accounting advice or a substitute for the restaurant’s accountant.',
    relatedSlugs: ['map-delivery-fees-to-chart-of-accounts', 'third-party-delivery-month-end-close-checklist'],
    sources: [{ title: 'DoorDash: Statement categories and net-total formula', url: DD_STATEMENT }, { title: 'Uber Eats Manager: Sales and fee breakdown', url: UBER_SALES }],
  }),
  guide({
    id: -39,
    week: 39,
    category: 'Close and accounting',
    slug: 'map-delivery-fees-to-chart-of-accounts',
    title: 'How to map delivery-marketplace costs to the chart of accounts',
    question: 'Which third-party delivery statement categories should remain separate in restaurant accounting?',
    summary: 'Use stable accounts for commission, merchant fees, marketing, restaurant-funded discounts, refunds, adjustments, and fee taxes while preserving platform detail.',
    answer: 'A useful mapping keeps categories with different owners and decisions separate. Commission and contractual service fees belong apart from marketing fees and restaurant-funded discounts. Refunds or error charges should remain visible from other adjustments. Fee taxes should not be mixed with order-subtotal taxes, and tips or other pass-throughs should follow the restaurant’s approved accounting policy.\n\nUse platform and location dimensions under the stable accounts instead of creating a new general-ledger account for every report label. Maintain a mapping table with source field, sign, destination account, effective date, and reviewer. When a platform changes a label, update the map without rewriting prior periods.',
    audience: 'restaurant controller, accountant, or CFO',
    keywords: ['delivery fees chart of accounts', 'DoorDash accounting categories', 'restaurant marketplace expense accounts', '3P accounting'],
    fieldChecks: ['Define stable economic categories.', 'Map every source field with sign and effective date.', 'Review unmapped or changed labels before posting.'],
    evidenceNeeded: ['Platform field dictionary', 'Restaurant chart of accounts', 'Approved mapping table'],
    evidenceBoundary: 'The right final account treatment depends on the restaurant’s accounting policy and jurisdiction.',
    relatedSlugs: ['book-third-party-delivery-gross-not-net', 'separate-tips-taxes-and-pass-through-amounts'],
    sources: [{ title: 'DoorDash: Financial data terminology', url: DD_STATEMENT }, { title: 'Uber Eats Manager: Payment Details fields', url: UBER_REPORTS }],
  }),
  guide({
    id: -40,
    week: 40,
    category: 'Taxes and pass-throughs',
    slug: 'separate-tips-taxes-and-pass-through-amounts',
    title: 'How to separate tips, taxes, and pass-through amounts in a 3P audit',
    question: 'Why should tips, customer fees, and taxes be removed from some delivery-fee denominators?',
    summary: 'A fee-rate test must use the eligible base defined by the agreement; customer or government pass-through amounts can distort the rate.',
    answer: 'Statements can include food subtotal, sales tax, customer fees, tips, and other amounts that the restaurant may not economically retain. Before calculating a commission or all-in marketplace-cost rate, define the sales base and separate pass-through amounts. Use the governing agreement for a contract test and disclose the denominator used for any observed-rate calculation.\n\nTwo analysts can produce different percentages from the same statement if one divides by gross order value and another by eligible food sales. Show both the numerator and denominator, identify each excluded amount, and refuse a contract conclusion when the rate base is missing.',
    audience: 'restaurant owner, accountant, or finance analyst',
    keywords: ['DoorDash commission denominator', 'delivery tips taxes', 'marketplace eligible sales', 'restaurant fee calculation'],
    formula: 'Observed rate = named marketplace charge ÷ disclosed eligible-sales base',
    fieldChecks: ['Classify tips, taxes, and customer-funded amounts.', 'Document the denominator for every rate.', 'Use the contract-defined base for compliance testing.'],
    evidenceNeeded: ['Statement categories', 'Eligible-sales definition', 'Agreement or rate card for contract testing'],
    evidenceBoundary: 'A percentage without its denominator is not a defensible fee-rate conclusion.',
    relatedSlugs: ['delivery-marketplace-commission-overcharge-proof', 'calculate-true-third-party-delivery-cost'],
    sources: [{ title: 'DoorDash: Sales, tax, fee, and marketing terminology', url: DD_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -41,
    week: 41,
    category: 'Completeness controls',
    slug: 'find-duplicate-or-missing-marketplace-settlements',
    title: 'How to find duplicate or missing marketplace settlements',
    question: 'What completeness checks catch a missing store, duplicated file, or omitted payout before the dollar reconciliation begins?',
    summary: 'Test unique payout IDs, store-period coverage, file hashes, row counts, and sequence gaps before summing money.',
    answer: 'A total can look reasonable even when one store is missing and another file was loaded twice. Build a completeness manifest listing platform, legal entity, store ID, statement or payout ID, covered dates, file name, row count, and a file hash when available. Reject duplicate IDs or hashes and flag gaps in expected weekly or monthly coverage.\n\nCompare the active-store master with the stores present in each close. Then reconcile dollars. Completeness is a separate control because no amount of accurate arithmetic can recover a file that was never included.',
    audience: 'multi-unit controller, analyst, or CTO',
    keywords: ['missing DoorDash payout', 'duplicate marketplace statement', 'restaurant reconciliation completeness', 'payout manifest'],
    fieldChecks: ['Create the source-file manifest.', 'Test unique payout IDs and file hashes.', 'Compare expected stores and periods with received coverage.'],
    evidenceNeeded: ['Active store-platform master', 'Raw file manifest', 'Expected settlement calendar'],
    evidenceBoundary: 'A tied total does not prove completeness or uniqueness.',
    relatedSlugs: ['reconcile-doordash-across-multiple-locations', 'third-party-delivery-month-end-close-checklist'],
    sources: [{ title: 'DoorDash: Payout IDs and finalized detail', url: DD_FINANCIALS }, { title: 'Uber Eats Manager: Report store and date selection', url: UBER_REPORTS }],
  }),
  guide({
    id: -42,
    week: 42,
    category: 'Payout reconciliation',
    slug: 'marketplace-payouts-that-cross-month-end',
    title: 'How to handle delivery payouts that cross month-end',
    question: 'What should a restaurant do when one marketplace payout contains transactions from two accounting months?',
    summary: 'Allocate activity by transaction date for the month close and preserve the payout as the cash-clearing unit.',
    answer: 'Use transaction-level dates to assign sales, fees, promotions, refunds, and adjustments to the appropriate activity month, while keeping the finalized payout ID intact for bank clearing. The month-end schedule should show the portion earned but not yet deposited and the portion from the prior month included in the current deposit.\n\nDo not split the actual bank transaction into invented deposits. Instead, maintain a subledger that connects monthly activity to the real payout. DoorDash specifically notes that payout periods can straddle months, which is why monthly statements and deposits dated in the month can differ.',
    audience: 'restaurant accountant or controller',
    keywords: ['DoorDash payout month end', 'delivery settlement accrual', 'restaurant cutoff reconciliation', 'payout period'],
    formula: 'Month activity + opening unsettled balance − closing unsettled balance = cash assigned to the month',
    fieldChecks: ['Assign transactions by the approved cutoff rule.', 'Keep payout IDs intact for cash matching.', 'Roll unsettled balances by platform and store.'],
    evidenceNeeded: ['Transaction-level dates', 'Finalized payout composition', 'Month-end bank activity'],
    evidenceBoundary: 'A timing difference should not be relabeled as a fee or shortage.',
    relatedSlugs: ['doordash-monthly-statement-vs-payout-period', 'third-party-delivery-month-end-close-checklist'],
    sources: [{ title: 'DoorDash: Monthly statements versus payout periods', url: DD_STATEMENT }, { title: "Never86'd payout reconciliation guide", url: 'https://www.never86.ai/answers/reconcile-doordash-payout-to-bank-deposit' }],
  }),
  guide({
    id: -43,
    week: 43,
    category: 'Payout reconciliation',
    slug: 'match-one-marketplace-payout-to-multiple-bank-deposits',
    title: 'How to match combined or split marketplace deposits',
    question: 'What should a restaurant do when one marketplace payout does not match one bank transaction?',
    summary: 'Use a many-to-many bridge with payout IDs, deposit references, dates, and amounts instead of forcing a false one-to-one match.',
    answer: 'Some cash flows can combine multiple stores or settlements into one deposit, while other situations can split a payment. Build a bridge table where each row links a payout ID and amount to a bank transaction reference and amount. Require the sum of linked components to reconcile on both sides.\n\nUse dates as a search aid, not the only matching rule. Preserve partial matches and unexplained residuals explicitly. If the platform payout total is correct but the bank bridge remains open, the exception is cash matching—not automatically a marketplace-fee problem.',
    audience: 'restaurant bookkeeper, controller, or finance analyst',
    keywords: ['combined DoorDash deposit', 'split marketplace payout', 'many to many reconciliation', 'restaurant bank matching'],
    formula: 'Sum of linked payout components = sum of linked bank-deposit components',
    fieldChecks: ['Assign stable IDs to both payouts and bank transactions.', 'Allow many-to-many links.', 'Carry residuals with owner and aging.'],
    evidenceNeeded: ['Payout IDs and amounts', 'Bank transaction references', 'Bridge schedule'],
    evidenceBoundary: 'A non-one-to-one cash pattern is not itself a shortage.',
    relatedSlugs: ['investigate-missing-or-delayed-doordash-payout', 'reconcile-uber-eats-payout-to-bank'],
    sources: [{ title: 'DoorDash: Finalized payout detail', url: DD_FINANCIALS }, { title: 'Uber Eats Manager: Payment date and amount owed', url: UBER_SALES }],
  }),
  guide({
    id: -44,
    week: 44,
    category: 'Disputes and controls',
    slug: 'build-restaurant-delivery-dispute-packet',
    title: 'How to build a restaurant delivery dispute packet',
    question: 'What makes a DoorDash, Uber Eats, or Grubhub payment dispute easy to understand and defend?',
    summary: 'Lead with one bounded claim, the governing rule, source rows, reproducible math, and the exact requested correction.',
    answer: 'A useful dispute packet names the platform, store, order or payout ID, period, issue type, observed amount, expected amount, difference, and requested action. Attach the statement rows and restaurant-held evidence. If the claim depends on a contract, include the applicable rate or clause and the eligible-sales calculation.\n\nKeep one issue per packet when possible. Use neutral language and distinguish verified facts, calculations, and missing evidence. Record submission date, support case ID, response, and any later credit. The packet should let another person reproduce the claim without a meeting.',
    audience: 'restaurant owner, controller, or counsel',
    keywords: ['DoorDash dispute packet', 'Uber Eats payment dispute', 'restaurant marketplace claim', 'delivery fee evidence'],
    formula: 'Claimed difference = evidence-supported expected amount − platform-observed amount',
    fieldChecks: ['State one bounded issue and requested action.', 'Attach source rows and governing evidence.', 'Track the case through final payout resolution.'],
    evidenceNeeded: ['Statement or order rows', 'Contract or policy when relevant', 'Support case and resolution trail'],
    evidenceBoundary: 'Do not claim fraud, theft, or contract violation when the governing evidence is incomplete.',
    relatedSlugs: ['delivery-marketplace-commission-overcharge-proof', 'review-doordash-error-charges'],
    sources: [{ title: 'DoorDash: Error-charge review process', url: DD_ERRORS }, { title: 'Uber: Weekly pay statement issues', url: UBER_ERRORS }, { title: "Never86'd evidence standard", url: 'https://www.never86.ai/story' }],
  }),
  guide({
    id: -45,
    week: 45,
    category: 'Disputes and controls',
    slug: 'retain-marketplace-statements-and-audit-evidence',
    title: 'How to retain marketplace statements and audit evidence',
    question: 'What files should a restaurant preserve so a delivery payout or fee question can be reproduced later?',
    summary: 'Keep the raw export, redacted working copy, contract version, calculation, bank support, and resolution log with stable identifiers.',
    answer: 'Preserve the original finalized statement or report in a restricted location, plus a redacted working copy for analysis. Keep the applicable contract or rate card, store and payout identifiers, calculation workbook or machine-readable result, matching bank evidence, support case, and final resolution. Record who produced the file and when.\n\nDo not overwrite raw exports with cleaned versions. Use a retention period approved by the restaurant’s accountant, counsel, and privacy policy. Access should be limited by role, and shared files should exclude credentials, full bank details, tax IDs, and unnecessary guest information.',
    audience: 'restaurant controller, owner, CTO, or counsel',
    keywords: ['restaurant statement retention', 'DoorDash audit evidence', 'marketplace data privacy', 'delivery reconciliation records'],
    fieldChecks: ['Separate immutable originals from redacted working copies.', 'Version contracts and calculations.', 'Link support resolution back to the original exception.'],
    evidenceNeeded: ['Raw and redacted files', 'Retention and access policy', 'Exception-resolution index'],
    evidenceBoundary: 'Never86’d does not set the restaurant’s legal record-retention period.',
    relatedSlugs: ['what-to-redact-from-restaurant-statement-before-ai-audit', 'build-restaurant-delivery-dispute-packet'],
    sources: [{ title: 'Uber: Reports are downloaded from Reports Hub', url: UBER_REPORTS }, { title: "Never86'd statement-redaction guide", url: 'https://www.never86.ai/answers/what-to-redact-from-restaurant-statement-before-ai-audit' }],
  }),
  guide({
    id: -46,
    week: 46,
    category: 'Promotions and marketing',
    slug: 'measure-delivery-promotion-roi',
    title: 'How to measure third-party delivery promotion ROI',
    question: 'What is the minimum evidence needed to decide whether a DoorDash, Uber Eats, or Grubhub promotion helped?',
    summary: 'Reconcile campaign funding first, then compare incremental contribution with a credible baseline and disclose uncertainty.',
    answer: 'Begin with campaign setup, dates, stores, eligible items, funding split, marketing fees, credits, and restaurant-funded discounts. Reconcile those costs to the statement. Choose a comparison that accounts for normal daypart, weekday, seasonality, menu availability, and store changes.\n\nEstimate incremental contribution, not just sales. Subtract platform costs, restaurant-funded incentives, food and packaging cost, and incremental labor. Track whether promoted guests returned without another discount only when customer-level data is available and permitted. If the baseline or attribution is weak, publish a range or an unresolved result.',
    audience: 'restaurant marketer, CFO, or owner',
    keywords: ['delivery promotion ROI', 'DoorDash promo profitability', 'Uber Eats marketing ROI', 'restaurant discount contribution'],
    formula: 'Promotion ROI = estimated incremental contribution ÷ restaurant-funded campaign cost',
    fieldChecks: ['Reconcile restaurant-funded campaign cost.', 'Define a comparable baseline.', 'Report contribution and uncertainty, not sales alone.'],
    evidenceNeeded: ['Campaign terms and funding split', 'Statement charges and credits', 'Comparable sales and cost data'],
    evidenceBoundary: 'Correlation during a promotion is not proof the promotion caused the sales lift.',
    relatedSlugs: ['audit-doordash-marketing-spend', 'audit-uber-eats-promotions-and-credits'],
    sources: [{ title: 'DoorDash: Marketing funding and credits', url: DD_STATEMENT }, { title: 'Uber Eats Manager: Payment Details', url: UBER_REPORTS }],
  }),
  guide({
    id: -47,
    week: 47,
    category: 'Channel economics',
    slug: 'calculate-profit-by-delivery-platform',
    title: 'How to compare profit by delivery platform',
    question: 'How can a restaurant compare DoorDash, Uber Eats, and Grubhub economics without relying on commission alone?',
    summary: 'Normalize stores, periods, sales bases, statement costs, refunds, promotions, and restaurant fulfillment costs before comparing contribution.',
    answer: 'Use the same stores and time period for every platform. Start with eligible food sales, then subtract platform commission and fees, restaurant-funded marketing and promotions, refunds or error charges, and other deductions. Add restaurant-held estimates for food, packaging, incremental labor, and delivery expense only when they can be applied consistently.\n\nShow dollars and rates, volume, average order value, and contribution. Keep platform-funded discounts and pass-through taxes separate. The best platform is not automatically the one with the lowest fee rate; mix, volume, guest behavior, and operational burden can change the decision.',
    audience: 'restaurant owner, CFO, or channel leader',
    keywords: ['DoorDash vs Uber Eats profit', 'Grubhub profitability', 'delivery platform comparison', 'restaurant channel contribution'],
    formula: 'Estimated channel contribution = eligible sales − observed platform costs − restaurant-funded incentives − attributable fulfillment costs',
    fieldChecks: ['Normalize period, stores, and denominator.', 'Separate every platform cost category.', 'Add comparable restaurant-held fulfillment costs.'],
    evidenceNeeded: ['Finalized platform statements', 'Comparable store and period scope', 'Restaurant cost assumptions with sources'],
    evidenceBoundary: 'A statement audit measures marketplace economics; full profit requires restaurant cost evidence outside the statement.',
    relatedSlugs: ['compare-doordash-uber-eats-grubhub-like-for-like', 'calculate-delivery-menu-item-contribution'],
    sources: [{ title: 'DoorDash: Statement financial categories', url: DD_STATEMENT }, { title: 'Uber Eats Manager: Payment Details report', url: UBER_REPORTS }, { title: 'Grubhub: Financial statement sections', url: GH_STATEMENT }],
  }),
  guide({
    id: -48,
    week: 48,
    category: 'Channel economics',
    slug: 'calculate-delivery-menu-item-contribution',
    title: 'How to calculate delivery menu-item contribution',
    question: 'Can a marketplace statement show which menu items are profitable for delivery?',
    summary: 'A statement supplies sales and deductions; item contribution also needs item mix, modifiers, food, packaging, and labor evidence.',
    answer: 'A marketplace statement alone usually cannot prove item-level profitability. Combine order or item detail with current recipe cost, packaging cost, platform-specific menu price, restaurant-funded discounts, refund or error behavior, and an approved method for allocating platform fees and incremental labor.\n\nStart with high-volume or high-error items instead of spreading weak assumptions across the full menu. Show contribution before fixed overhead and identify estimated inputs. An item can have strong sales but poor contribution because of discounts, packaging, error charges, or an outdated digital price.',
    audience: 'restaurant chef, CFO, owner, or menu leader',
    keywords: ['delivery menu profitability', 'DoorDash item margin', 'restaurant packaging cost', 'third party menu contribution'],
    formula: 'Estimated item contribution = item revenue − allocated platform costs − restaurant-funded discount − food − packaging − attributable labor and error cost',
    fieldChecks: ['Join item-level marketplace and POS detail.', 'Use current recipe and packaging cost.', 'Flag assumptions and start with material items.'],
    evidenceNeeded: ['Item-level orders', 'Recipe and packaging cost', 'Allocation method for fees and labor'],
    evidenceBoundary: 'Statement-level cost does not become item-level profit without restaurant-held cost and mix evidence.',
    relatedSlugs: ['calculate-profit-by-delivery-platform', 'set-delivery-menu-prices-from-evidence'],
    sources: [{ title: 'Uber Eats Manager: Order and item-level reports', url: UBER_REPORTS }, { title: 'DoorDash: Order-item detail reporting', url: DD_STATEMENT }],
  }),
  guide({
    id: -49,
    week: 49,
    category: 'Channel economics',
    slug: 'set-delivery-menu-prices-from-evidence',
    title: 'How to set delivery menu prices from evidence',
    question: 'What should a restaurant calculate before raising marketplace menu prices to offset fees?',
    summary: 'Use actual channel cost, item contribution, demand response, contract terms, and guest value rather than applying one markup to every item.',
    answer: 'First measure observed marketplace cost by platform and the current contribution of major menu items. Separate commission, marketing, promotions, refunds, error charges, and fulfillment costs. Review the governing agreement and marketplace rules before changing prices. Then test item-level price scenarios, not one blanket percentage.\n\nA markup can protect contribution but can also affect demand, conversion, guest trust, and relative value. Start with a bounded group of items, record the effective date, and compare order volume and contribution with a stable baseline. Do not claim an optimal markup without demand evidence.',
    audience: 'restaurant owner, CFO, or menu leader',
    keywords: ['DoorDash menu markup', 'delivery menu pricing', 'restaurant marketplace prices', 'third party fee recovery'],
    fieldChecks: ['Measure actual channel and item economics.', 'Review applicable agreement and marketplace rules.', 'Test bounded price changes and monitor contribution.'],
    evidenceNeeded: ['Platform cost by category', 'Item cost and order history', 'Applicable agreement and test results'],
    evidenceBoundary: 'Observed fees can inform pricing; they do not prove the demand response or an optimal markup.',
    relatedSlugs: ['calculate-delivery-menu-item-contribution', 'calculate-true-third-party-delivery-cost'],
    sources: [{ title: 'DoorDash: Commission, marketing, and amendment categories', url: DD_STATEMENT }, { title: "Never86'd true-cost guide", url: 'https://www.never86.ai/answers/calculate-true-third-party-delivery-cost' }],
  }),
  guide({
    id: -50,
    week: 50,
    category: 'Channel economics',
    slug: 'when-high-delivery-fees-are-not-the-whole-problem',
    title: 'When high delivery fees are not the whole problem',
    question: 'What else should a restaurant test when third-party delivery feels unprofitable?',
    summary: 'Fees may be material, but promotions, refunds, menu pricing, food cost, packaging, labor, cancellations, and order mix can produce the larger operational gap.',
    answer: 'Start by separating observed marketplace costs: commission, other fees, marketing, restaurant-funded promotions, refunds, error charges, and adjustments. Then inspect restaurant-controlled economics such as digital menu price, item mix, recipe cost, packaging, labor, cancellation behavior, missed-item patterns, and handoff execution.\n\nThe right next action depends on the source. A contract-rate discrepancy belongs with finance; a promotion problem belongs with marketing; repeated missing-item charges belong with operations. Calling every cost “the fee” hides ownership and can send the team after the wrong fix.',
    audience: 'restaurant owner, operator, CFO, or COO',
    keywords: ['third party delivery unprofitable', 'DoorDash fees restaurant', 'delivery margin problem', 'restaurant marketplace economics'],
    fieldChecks: ['Split marketplace costs by cause.', 'Add restaurant-controlled contribution inputs.', 'Route each material issue to the person who can act.'],
    evidenceNeeded: ['Finalized statement', 'Item and operating cost data', 'Owner and resolution log'],
    evidenceBoundary: 'Total marketplace cost is not automatically an error, contract violation, or recoverable leakage.',
    relatedSlugs: ['calculate-true-third-party-delivery-cost', 'restaurant-command-center-without-another-dashboard'],
    sources: [{ title: 'DoorDash: Financial category definitions', url: DD_STATEMENT }, { title: "Never86'd operator action model", url: 'https://www.never86.ai/answers/restaurant-command-center-without-another-dashboard' }],
  }),
  guide({
    id: -51,
    week: 51,
    category: 'Disputes and controls',
    slug: 'how-often-restaurants-should-audit-delivery-payouts',
    title: 'How often restaurants should audit delivery payouts',
    question: 'Should an independent restaurant reconcile third-party delivery weekly, monthly, or only when something looks wrong?',
    summary: 'Use a light weekly payout-to-bank control and a deeper monthly statement close; increase review when volume, changes, or unresolved exceptions rise.',
    answer: 'For an active marketplace, a practical minimum is a weekly completeness and cash check: confirm finalized payouts, expected deposits, and any missing or delayed item. At month-end, complete the deeper category reconciliation, timing bridge, tax separation, adjustment review, and exception aging.\n\nA one-location owner may sample low-risk order detail while reviewing every material variance. A multi-unit group should automate completeness and thresholding but still preserve human review for contract, policy, or evidence-dependent conclusions. Audit frequency should increase after a rate change, promotion launch, bank change, platform migration, acquisition, or recurring mismatch.',
    audience: 'independent restaurant owner or multi-unit controller',
    keywords: ['how often audit DoorDash', 'weekly payout reconciliation', 'restaurant marketplace controls', 'monthly delivery close'],
    fieldChecks: ['Run weekly completeness and cash checks.', 'Run monthly category and timing reconciliation.', 'Escalate cadence after changes or repeated exceptions.'],
    evidenceNeeded: ['Payout calendar', 'Materiality thresholds', 'Exception history'],
    evidenceBoundary: 'The right cadence depends on volume, staffing, risk, and the restaurant’s accounting policy.',
    relatedSlugs: ['third-party-delivery-month-end-close-checklist', 'first-30-minutes-of-a-marketplace-payout-investigation'],
    sources: [{ title: 'DoorDash: Finalized payouts for regular reconciliation', url: DD_FINANCIALS }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
  guide({
    id: -52,
    week: 52,
    category: 'Start here',
    slug: 'first-30-minutes-of-a-marketplace-payout-investigation',
    title: 'The first 30 minutes of a marketplace payout investigation',
    question: 'What is the fastest defensible way for a busy restaurant operator to investigate a confusing 3P payout?',
    summary: 'Define one question, pull one finalized statement, protect sensitive data, rebuild the money path, and name the next missing record.',
    answer: 'Start with one platform, one store, one finalized payout or statement, and one question. Redact credentials and unnecessary personal information while preserving financial rows, dates, store, order, payout, and adjustment references. Recalculate sales, marketplace costs, amendments, and expected payout, then compare the matching bank evidence if available.\n\nLabel every result Verified, Calculated, or Missing. Do not widen the investigation until the first money path is clear. End with no more than three next actions: the record needed, the person who owns it, and the date to review the result. This is the small-operator wedge: one useful answer before an integration or software project.',
    audience: 'busy independent restaurant owner or operator',
    keywords: ['help with DoorDash payout', 'restaurant delivery statement help', '3P payout investigation', 'DoorDash audit first step'],
    formula: 'One statement → categorized deductions → expected payout → bank match → one owned next action',
    fieldChecks: ['Choose one bounded payout question.', 'Redact safely and preserve the evidence rows.', 'Finish with the next missing record and owner.'],
    evidenceNeeded: ['One finalized redacted statement', 'Matching deposit when testing cash', 'Contract only when testing a rate'],
    evidenceBoundary: 'The first pass explains what the supplied evidence supports. It does not guarantee savings, recovery, or complete platform coverage.',
    relatedSlugs: ['audit-doordash-fees-without-portal-login', 'what-to-redact-from-restaurant-statement-before-ai-audit'],
    sources: [{ title: 'DoorDash: Finalized financial data', url: DD_FINANCIALS }, { title: 'Uber Eats Manager: Payment Details report', url: UBER_REPORTS }, { title: 'Grubhub: Financial statement overview', url: GH_STATEMENT }, { title: "Never86'd Marketplace Audit", url: AUDIT }],
  }),
];
