/**
 * Keep / kill / replace catalog for the v1 rebuild.
 * Cursor cloud rows are recommendations only — this module does not archive live agents.
 */

import type { InventoryRow } from './types';

export const ORCHESTRATION_INVENTORY: readonly InventoryRow[] = [
  {
    id: 'supervisor',
    name: 'Supervisor',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Route one intent to one specialist. Never compute dollars.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Canonical v1 seat. Replaces store-chief-of-staff / source-collector / margin-analyst / truth-qa as addressable agents.',
  },
  {
    id: 'labor',
    name: 'Labor',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Schedule vs clock vs hourly sales. Never discipline.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Keeps analyze_labor. Absorbs Labor Leak product as a CSV surface, not a second seat.',
  },
  {
    id: 'vendor',
    name: 'Vendor',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Invoice drift, silence, pour/recipe truth. Invoice ≠ COGS.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Replaces beverage + food-invoice + recipe-cost specialist seats. Tools stay on public MCP.',
  },
  {
    id: 'voids',
    name: 'Voids',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Void/comp pattern vs this store peer band. Not a verdict.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Orchestration seat. /agents/void-hunter stays the public CSV product.',
  },
  {
    id: 'action-shift',
    name: 'Action Shift',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Yesterday → one action → night proof.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Replaces human-coach / operator-coach / proof-verifier as addressable agents.',
  },
  {
    id: 'memory',
    name: 'Memory',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Human-approved source-tagged rules, operator_id scoped, never deleted.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Replaces memory-curator. Map-backed now; Neon draft SQL 0008 not applied.',
  },
  {
    id: 'list-free-agents',
    name: 'Public CSV product catalog',
    kind: 'mcp',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Ten CSV leak hunters on /agents and /trial.',
    status: 'live',
    disposition: 'keep',
    note: 'Product, not factory seats. list_free_agents unchanged.',
  },
  {
    id: 'public-mcp',
    name: 'Never86 Operator System MCP',
    kind: 'mcp',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Read-only knowledge + analysis at /api/mcp.',
    status: 'live',
    disposition: 'keep',
    note: 'https://www.never86.ai/api/mcp. Do not bundle hunter/sales-org tools here.',
  },
  {
    id: 'company-org',
    name: 'Company GTM seats',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Sales / GTM / social / audit / product drafts for Myke.',
    status: 'live-in-git',
    disposition: 'keep',
    note: 'Company lane only. Removed from default operator list_agent_jobs store team.',
  },
  {
    id: 'command-center-swarm',
    name: 'Sample Store One swarm runner',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Deterministic CSV demo of the old six-seat store team.',
    status: 'live-in-git',
    disposition: 'archive',
    note: 'Keep /action-shift/swarm as the sample runner. Duplicate /command-center/swarm is archived.',
  },
  {
    id: 'legacy-agents-md',
    name: 'agents/*.md four-tier manifests',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Old toast/clover/looker specialist folklore.',
    status: 'archived',
    disposition: 'archive',
    note: 'Moved to archive/agents-v0/. Not customer-facing. Conflicts with one-job v1.',
  },
  {
    id: 'design-qa',
    name: 'Owner desk design QA',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Orange #E66B27 Owner-desk critique.',
    status: 'killed',
    disposition: 'kill',
    note: 'Not an operator job. Orange leftover. Alias returns null.',
  },
  {
    id: 'bamba-swarm',
    name: 'Bamba sales-labor swarm',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Lane C isolated 16-store desk.',
    status: 'live-in-git',
    disposition: 'keep',
    note: 'Tenant-isolated. Not the operator OS. Do not mix CTAP tokens.',
  },
  {
    id: 'overnight-coordinator',
    name: 'Overnight 7:00 AM coordinator',
    kind: 'cursor-cloud',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Overnight scorecard that missed staff-auth and four-LLM proof.',
    status: 'obsolete',
    disposition: 'kill',
    note: 'Handoff already marked obsolete. Do not relaunch.',
  },
  {
    id: 'grok-sales-org',
    name: 'Grok sales organization',
    kind: 'cursor-cloud',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Stale factory slot / local parser claims.',
    status: 'stale',
    disposition: 'kill',
    note: 'bc-01a03102-d4db-752a-ade6-d20e7aae1f71. No parser SHA/PR. Do not relaunch.',
  },
  {
    id: 'current-system-context',
    name: 'Current system context',
    kind: 'cursor-cloud',
    repo: 'wrong-repo / Agent-ctap-marketing',
    purpose: 'Wrong-repo context worker.',
    status: 'archived',
    disposition: 'kill',
    note: 'Already archived. Do not resume.',
  },
  {
    id: 'cursor-one-off-testers',
    name: 'Idle Cursor browser / video / secret-hunt testers',
    kind: 'cursor-cloud',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'One-off GUI, video, and login probes (~140 IDLE).',
    status: 'idle',
    disposition: 'archive',
    note: '148 accessible never86 agents as of 2026-09-05. Do not relaunch. Cap stays 1 writer. This rebuild does not archive them remotely.',
  },
  {
    id: 'cursor-factory-writers',
    name: 'Named Never86 factory writers',
    kind: 'cursor-cloud',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Bounded PRs already shipped or parked.',
    status: 'idle',
    disposition: 'archive',
    note: 'History only. Next writer uses the v1 registry. This run is the sole RUNNING writer.',
  },
  {
    id: 'cursor-automations-1-8',
    name: 'Cursor Automations recipes 1–8',
    kind: 'automation',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Sales/GTM/YouTube/Audit draft recipes in CURSOR_AUTOMATIONS.md.',
    status: 'documented-not-live-verified',
    disposition: 'keep',
    note: 'Company lane. Stops at Myke approval. Apollo mention is stale — Sentia+ is CRM.',
  },
  {
    id: 'vercel-cron-briefing',
    name: 'Vercel cron /api/briefing',
    kind: 'automation',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Daily briefing path.',
    status: 'configured',
    disposition: 'keep',
    note: 'Read path. This PR does not change production crons.',
  },
  {
    id: 'vercel-cron-followups',
    name: 'Vercel cron /api/cron/send-followups',
    kind: 'automation',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Scheduled follow-up send.',
    status: 'configured',
    disposition: 'freeze',
    note: 'Auto-send risk. Hold until Myke re-approves. Not disabled from this PR.',
  },
  {
    id: 'github-ci',
    name: 'GitHub CI verify',
    kind: 'automation',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Lint, vitest, production build.',
    status: 'live',
    disposition: 'keep',
    note: '.github/workflows/ci.yml',
  },
  {
    id: 'github-indexnow',
    name: 'GitHub IndexNow',
    kind: 'automation',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Search ping after deploy.',
    status: 'live',
    disposition: 'keep',
    note: 'AEO path. No new search-page work in this PR.',
  },
  {
    id: 'grok-bot-routines',
    name: 'Grok Bot social routines',
    kind: 'automation',
    repo: 'xAI Grok Bot workspaces',
    purpose: 'LinkedIn/Facebook/X/TikTok/YouTube draft routines.',
    status: 'mixed',
    disposition: 'keep',
    note: 'Facebook deferred. TikTok paused. X daily draft spec built, enablement unverified. No publish.',
  },
  {
    id: 'grok-bot-restaurant-scout',
    name: 'grok-bot-restaurant-scout',
    kind: 'external-repo',
    repo: 'mykemueller1-ctrl/grok-bot-restaurant-scout',
    purpose: 'TikTok shop scout + 238 pain-shopper agents + report-ops.',
    status: 'separate-repo',
    disposition: 'freeze',
    note: 'Do not import into never86 OS. Fourth-repo / mega-agent risk. GTM only if Myke asks.',
  },
  {
    id: 'agent-ctap-marketing',
    name: 'Agent-ctap-marketing',
    kind: 'external-repo',
    repo: 'mykemueller1-ctrl/Agent-ctap-marketing',
    purpose: 'Wrong-repo marketing thread.',
    status: 'do-not-use',
    disposition: 'kill',
    note: 'Never a Never86 product writer. Already archived in Cursor.',
  },
  {
    id: 'house-code-portal',
    name: 'CTAP house-code portal',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'CTAP community house-code door. Not the stranger free-seat funnel.',
    status: 'fail-closed',
    disposition: 'keep',
    note: '/portal. /communities redirects here. No live codes in git. Strangers and CTAP seat 1 use /onboard email.',
  },
  {
    id: 'email-first-funnel',
    name: 'Email-first public funnel',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Homepage and nav claim the free owner seat by email. No sandbox-first CTA.',
    status: 'drafted',
    disposition: 'keep',
    note: 'Primary CTA /onboard. Play and Owner desk stay URLs, not stranger doors.',
  },
  {
    id: 'simple-owner-demo',
    name: 'SimpleOwnerDemo real ask/upload',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Owner desk composer posts to /api/ask and /api/upload.',
    status: 'merged-on-main',
    disposition: 'keep',
    note: 'PR #205 already on main. This rebuild preserves the live wiring.',
  },
  {
    id: 'communities-open-play',
    name: '/communities open-play seat',
    kind: 'in-repo',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Former multi-door play lobby from #199.',
    status: 'replaced',
    disposition: 'replace',
    note: 'Redirects to /portal. Open play is not a seat door.',
  },
  {
    id: 'rebuild-resume-v2',
    name: 'Never86 · never86-rebuild-resume-v2',
    kind: 'cursor-cloud',
    repo: 'mykemueller1-ctrl/never86',
    purpose: 'Resume the fresh rebuild on a clean main branch.',
    status: 'running',
    disposition: 'keep',
    note: 'bc-f77c70d0-9c34-47fd-9c3f-07c553f8fc9b. Prior v1 writer stays idle. Do not relaunch junk one-offs.',
  },
] as const;

export function listInventory(disposition?: InventoryRow['disposition']): InventoryRow[] {
  const rows = ORCHESTRATION_INVENTORY.map((row) => ({ ...row }));
  if (!disposition) return rows;
  return rows.filter((row) => row.disposition === disposition);
}
