CREATE TABLE `daily_sales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessDate` varchar(10) NOT NULL,
	`grandTotal` decimal(10,2),
	`tax` decimal(10,2),
	`pickupQty` int,
	`pickupAmount` decimal(10,2),
	`deliveryQty` int,
	`deliveryAmount` decimal(10,2),
	`barQty` int,
	`barAmount` decimal(10,2),
	`tableQty` int,
	`tableAmount` decimal(10,2),
	`totalQty` int,
	`totalAmount` decimal(10,2),
	`catFoodQty` int,
	`catFoodAmount` decimal(10,2),
	`catBeerQty` int,
	`catBeerAmount` decimal(10,2),
	`catLiquorQty` int,
	`catLiquorAmount` decimal(10,2),
	`catPopQty` int,
	`catPopAmount` decimal(10,2),
	`catLargePizzasQty` int,
	`catLargePizzasAmount` decimal(10,2),
	`laborHeadcount` int,
	`laborTotal` decimal(10,2),
	`laborPct` decimal(5,2),
	`voidsCount` int,
	`voidsAmount` decimal(10,2),
	`lateDeliveriesCount` int,
	`avgDeliveryTimeMin` int,
	`wasteCount` int,
	`wasteAmount` decimal(10,2),
	`discountCount` int,
	`discountTotal` decimal(10,2),
	`discountPct` decimal(5,2),
	`expectedCash` decimal(10,2),
	`creditCards` decimal(10,2),
	`creditCardTips` decimal(10,2),
	`payOuts` decimal(10,2),
	`tableOrders` int,
	`tableGuests` int,
	`avgGuestPerOrder` decimal(4,2),
	`avgPerGuest` decimal(8,2),
	`totalLastYear` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `daily_sales_id` PRIMARY KEY(`id`),
	CONSTRAINT `daily_sales_businessDate_unique` UNIQUE(`businessDate`)
);
--> statement-breakpoint
CREATE TABLE `hourly_sales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessDate` varchar(10) NOT NULL,
	`hour` varchar(20) NOT NULL,
	`orders` int,
	`total` decimal(10,2),
	`avgSales` decimal(10,2),
	`laborPct` decimal(5,2),
	`pickupQty` int,
	`pickupAmount` decimal(10,2),
	`deliveryQty` int,
	`deliveryAmount` decimal(10,2),
	`barQty` int,
	`barAmount` decimal(10,2),
	`tableQty` int,
	`tableAmount` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `hourly_sales_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_career_track` (
	`id` int AUTO_INCREMENT NOT NULL,
	`staffId` int NOT NULL,
	`track` enum('kitchen','pizza','foh','driver') NOT NULL,
	`currentLevel` int NOT NULL DEFAULT 1,
	`promotedAt` timestamp,
	`promotedById` int,
	`advancementReadinessScore` int NOT NULL DEFAULT 0,
	`nextLevelRequirements` json,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_career_track_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`staffId` int NOT NULL,
	`evaluatorId` int NOT NULL,
	`evaluatedAt` timestamp NOT NULL,
	`workQuality` int NOT NULL,
	`attendance` int NOT NULL,
	`jobKnowledge` int NOT NULL,
	`teamwork` int NOT NULL,
	`finishingTasks` int NOT NULL,
	`overallAttitude` int NOT NULL,
	`customerInteraction` int NOT NULL,
	`multitasking` int NOT NULL,
	`computerSkills` int NOT NULL,
	`averageScore` decimal(3,2),
	`overallSuccession` text,
	`needsImprovement` text,
	`employeeConcerns` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_evaluations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_skill_certifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`staffId` int NOT NULL,
	`skillName` varchar(200) NOT NULL,
	`skillCategory` enum('equipment','food_prep','service','management','safety') NOT NULL,
	`certifiedAt` timestamp NOT NULL,
	`certifiedById` int,
	`expiresAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_skill_certifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_training_completions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`staffId` int NOT NULL,
	`moduleId` int NOT NULL,
	`completedAt` timestamp NOT NULL,
	`trainerId` int,
	`assessmentScore` int,
	`passed` boolean NOT NULL DEFAULT false,
	`notes` text,
	`verifiedByManagerId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_training_completions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_training_modules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`category` enum('equipment','food_prep','service','management','safety') NOT NULL,
	`requiredForTrack` enum('kitchen','pizza','foh','driver','all') NOT NULL,
	`requiredForLevel` int NOT NULL DEFAULT 1,
	`estimatedMinutes` int,
	`assessmentType` enum('trainer_signoff','written_test','weight_check','checklist_completion','manager_observation','practical_demo') NOT NULL,
	`passingScore` int,
	`sourceDocument` varchar(300),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_training_modules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worker_write_ups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`staffId` int NOT NULL,
	`issuedById` int NOT NULL,
	`issuedAt` timestamp NOT NULL,
	`severity` enum('verbal','written','final','termination') NOT NULL,
	`category` enum('attendance','performance','conduct','safety','policy') NOT NULL,
	`description` text NOT NULL,
	`employeeResponse` text,
	`acknowledgedAt` timestamp,
	`followUpDate` timestamp,
	`resolvedAt` timestamp,
	`expiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `worker_write_ups_id` PRIMARY KEY(`id`)
);
