import type { OperatorSnapshot, OperatorView } from "./contracts.js";

const commonMetrics = [
  {
    label: "Net sales",
    value: "$12.8k",
    status: "neutral" as const,
    detail: "Synthetic preview only",
  },
  {
    label: "Labor",
    value: "29.4%",
    status: "watch" as const,
    detail: "1.4 pts over demo target",
  },
  {
    label: "Prime cost",
    value: "61.8%",
    status: "risk" as const,
    detail: "Above demo target band",
  },
  {
    label: "Open flags",
    value: "3",
    status: "watch" as const,
    detail: "One needs action today",
  },
];

const snapshots: Record<OperatorView, OperatorSnapshot> = {
  action_shift: {
    view: "action_shift",
    stateVersion: 1,
    isDemo: true,
    locationAlias: "Demo Location",
    businessDate: "2026-08-30",
    eyebrow: "ACTION SHIFT",
    title: "One leak. One action. One proof.",
    subtitle: "Never86 turns yesterday into the next operator move instead of another dashboard.",
    metrics: commonMetrics,
    leak: {
      title: "Late labor ran past the sales curve",
      severity: "high",
      summary: "The final two labor hours stayed flat while sales tapered, creating the clearest controllable variance in this demo shift.",
      dollarImpact: "$186 estimated exposure",
      confidence: 0.91,
    },
    action: {
      title: "Move one closer cut 45 minutes earlier tonight",
      ownerRole: "Shift manager",
      due: "Tonight",
      proofRequired: "Closing labor snapshot plus manager note",
      why: "It directly attacks the highest-confidence controllable leak without changing service coverage earlier in the shift.",
    },
    evidence: [
      { id: "ev-z", label: "POS close", source: "Z report", detail: "Sales curve and close totals parsed", status: "verified" },
      { id: "ev-labor", label: "Labor close", source: "Timeclock", detail: "Late-hour staffing compared with sales", status: "verified" },
      { id: "ev-proof", label: "Night proof", source: "Manager", detail: "Pending after tonight's close", status: "needs_review" },
    ],
    rows: [
      { label: "9-10 PM", current: "$1,140 sales / 5 staff", baseline: "$1,260 / 5", variance: "Watch", status: "watch" },
      { label: "10-11 PM", current: "$610 sales / 5 staff", baseline: "$860 / 4", variance: "Risk", status: "risk" },
      { label: "11-close", current: "$220 sales / 4 staff", baseline: "$410 / 3", variance: "Risk", status: "risk" },
    ],
    promptSuggestion: "Explain why the labor leak is the first action and what proof I should require tonight.",
  },
  vendor_drift: {
    view: "vendor_drift",
    stateVersion: 1,
    isDemo: true,
    locationAlias: "Demo Location",
    businessDate: "2026-08-30",
    eyebrow: "VENDOR DRIFT",
    title: "Price movement that deserves a call.",
    subtitle: "Compare invoice-line cost against the last clean baseline and rank only material drift.",
    metrics: [
      { label: "Lines checked", value: "42", status: "neutral", detail: "Synthetic invoice set" },
      { label: "Price flags", value: "4", status: "watch", detail: "Over demo tolerance" },
      { label: "Top drift", value: "+11.8%", status: "risk", detail: "High-use cheese item" },
      { label: "Exposure", value: "$274/wk", status: "risk", detail: "At current demo volume" },
    ],
    leak: {
      title: "Core cheese case moved 11.8% without a matching pack change",
      severity: "high",
      summary: "The price change is larger than the configured tolerance and the product remains a high-volume input, so the dollar exposure compounds quickly.",
      dollarImpact: "$188 weekly demo exposure",
      confidence: 0.96,
    },
    action: {
      title: "Challenge the cheese line before the next order",
      ownerRole: "Purchasing manager",
      due: "Before next truck cutoff",
      proofRequired: "Vendor response or corrected price attached to the item record",
      why: "The variance is material, repeatable and tied to a core ingredient rather than a low-use exception.",
    },
    evidence: [
      { id: "ev-invoice-new", label: "Current invoice", source: "Vendor invoice", detail: "$74.20 case equivalent", status: "verified" },
      { id: "ev-invoice-base", label: "Baseline invoice", source: "Vendor invoice", detail: "$66.37 case equivalent", status: "verified" },
      { id: "ev-pack", label: "Pack/UOM", source: "SKU crosswalk", detail: "No pack-size change detected", status: "verified" },
    ],
    rows: [
      { label: "Mozzarella case", current: "$74.20", baseline: "$66.37", variance: "+11.8%", status: "risk" },
      { label: "Fryer oil", current: "$32.10", baseline: "$31.55", variance: "+1.7%", status: "good" },
      { label: "Pizza boxes", current: "$56.80", baseline: "$54.90", variance: "+3.5%", status: "watch" },
      { label: "Chicken case", current: "$91.40", baseline: "$89.95", variance: "+1.6%", status: "good" },
    ],
    promptSuggestion: "Draft the vendor conversation for the flagged cheese price and tell me what evidence supports it.",
  },
  item_trace: {
    view: "item_trace",
    stateVersion: 1,
    isDemo: true,
    locationAlias: "Demo Location",
    businessDate: "2026-08-30",
    eyebrow: "ITEM TRACE",
    title: "Follow one item from ring to ingredient to vendor.",
    subtitle: "The crosswalk connects POS item, recipe, inventory item, vendor SKU and invoice evidence.",
    metrics: [
      { label: "POS item", value: "Matched", status: "good", detail: "Demo POS ID 1842" },
      { label: "Recipe", value: "v7", status: "good", detail: "Current demo version" },
      { label: "Vendor SKU", value: "Matched", status: "good", detail: "Primary source linked" },
      { label: "Cost change", value: "+6.2%", status: "watch", detail: "Since recipe recost" },
    ],
    leak: {
      title: "Recipe cost is stale against current ingredient cost",
      severity: "medium",
      summary: "The item trace is complete, but the recipe card has not been recosted since a key ingredient price moved.",
      dollarImpact: "$0.41 per order demo gap",
      confidence: 0.94,
    },
    action: {
      title: "Recost recipe v7 using the current vendor line",
      ownerRole: "Kitchen manager",
      due: "This week",
      proofRequired: "Approved recipe cost card with source invoice reference",
      why: "The crosswalk is already intact, so this is a fast correction that improves theoretical food-cost accuracy.",
    },
    evidence: [
      { id: "ev-pos", label: "POS ring", source: "POS", detail: "Demo item 1842 linked", status: "verified" },
      { id: "ev-recipe", label: "Recipe v7", source: "Recipe BOM", detail: "Ingredient quantities linked", status: "verified" },
      { id: "ev-sku", label: "Ingredient SKU", source: "Inventory", detail: "Vendor SKU crosswalk complete", status: "verified" },
      { id: "ev-cost", label: "Current cost", source: "Invoice", detail: "New unit cost is newer than recipe cost", status: "verified" },
    ],
    rows: [
      { label: "POS item", current: "1842 Demo Pizza", baseline: "Mapped", variance: "OK", status: "good" },
      { label: "Recipe", current: "Recipe v7", baseline: "Current", variance: "OK", status: "good" },
      { label: "Ingredient", current: "Mozzarella", baseline: "12 oz", variance: "OK", status: "good" },
      { label: "Vendor SKU", current: "DEMO-CHZ-01", baseline: "Primary", variance: "OK", status: "good" },
      { label: "Recipe unit cost", current: "$0.52/oz", baseline: "$0.49/oz", variance: "+6.2%", status: "watch" },
    ],
    promptSuggestion: "Walk me through this item trace and show which source should be treated as truth at each step.",
  },
  inventory_risk: {
    view: "inventory_risk",
    stateVersion: 1,
    isDemo: true,
    locationAlias: "Demo Location",
    businessDate: "2026-08-30",
    eyebrow: "INVENTORY RISK",
    title: "Catch the next 86 before service catches it.",
    subtitle: "Combine par, recent usage, on-hand count and truck timing into an operator-ready risk list.",
    metrics: [
      { label: "Items scanned", value: "128", status: "neutral", detail: "Synthetic inventory set" },
      { label: "High risk", value: "2", status: "risk", detail: "Likely below next-delivery need" },
      { label: "Watch", value: "5", status: "watch", detail: "Needs count or order check" },
      { label: "Next truck", value: "Tomorrow", status: "neutral", detail: "Demo supplier schedule" },
    ],
    leak: {
      title: "Pickles project below service need before the next truck",
      severity: "high",
      summary: "Current on-hand plus open order is below projected demand, and the item has a recent 86 pattern in the demo history.",
      dollarImpact: "Service-risk flag",
      confidence: 0.89,
    },
    action: {
      title: "Verify physical count and add one case if confirmed",
      ownerRole: "Opening manager",
      due: "Before order cutoff",
      proofRequired: "Count photo or checklist entry plus updated order quantity",
      why: "The model should not order from a stale count; a fast physical verification closes the uncertainty before committing spend.",
    },
    evidence: [
      { id: "ev-par", label: "Par", source: "Order guide", detail: "Demo par 8 units", status: "verified" },
      { id: "ev-count", label: "On hand", source: "Inventory count", detail: "Last count shows 2 units", status: "needs_review" },
      { id: "ev-usage", label: "Usage", source: "Sales + recipe", detail: "Projected demand 5 units", status: "verified" },
      { id: "ev-truck", label: "Truck timing", source: "Vendor schedule", detail: "Next receipt after projected need", status: "verified" },
    ],
    rows: [
      { label: "Pickles", current: "2 on hand", baseline: "Par 8", variance: "High risk", status: "risk" },
      { label: "Mozzarella", current: "5 cases", baseline: "Par 5", variance: "OK", status: "good" },
      { label: "Fryer oil", current: "2 cases", baseline: "Par 3", variance: "Watch", status: "watch" },
      { label: "Pizza boxes", current: "4 cases", baseline: "Par 4", variance: "OK", status: "good" },
    ],
    promptSuggestion: "Tell me whether I should order now or count first, and explain the evidence hierarchy.",
  },
};

export function getDemoSnapshot(view: OperatorView): OperatorSnapshot {
  return snapshots[view];
}
