import { getOperatorReport, type ToastReport } from '@/lib/toastReports';
import { opsDbConfigured } from '@/lib/opsDb';

const usd = (n: number) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);

const count = (n: number) => new Intl.NumberFormat('en-US').format(n);

const prettyDate = (iso: string) =>
  iso
    ? new Date(iso + 'T00:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
    : '—';

function Shell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-dark-800 px-6 py-12">
      <div className="max-w-4xl mx-auto">
        <p className="text-dark-300 text-sm uppercase tracking-wider mb-1">Never 86&apos;d · Live Toast Report</p>
        <h1 className="text-4xl font-bold text-gold-500 mb-6">{title}</h1>
        {children}
      </div>
    </main>
  );
}

function NotConnected({ error }: { error?: string }) {
  return (
    <Shell title="Live Toast Report">
      <div className="bg-dark-700 border border-dark-600 rounded-xl p-6">
        <p className="text-white font-semibold mb-2">Your live data isn&apos;t connected yet.</p>
        <p className="text-dark-300 text-sm mb-4">
          If you&apos;re seeing this, contact the team and we&apos;ll bring you online.
        </p>
        {error ? <p className="text-dark-400 text-xs font-mono break-all">{error}</p> : null}
      </div>
    </Shell>
  );
}

export default async function OperatorReportView({
  operatorId,
  displayName,
}: {
  operatorId: number;
  displayName?: string;
}) {
  if (!opsDbConfigured()) return <NotConnected />;

  let report: ToastReport;
  try {
    report = await getOperatorReport(operatorId, displayName);
  } catch (err: any) {
    return <NotConnected error={err?.message ?? String(err)} />;
  }

  if (report.locationCount === 0) {
    return (
      <Shell title={report.operatorName}>
        <div className="bg-dark-700 border border-dark-600 rounded-xl p-6">
          <p className="text-white font-semibold mb-1">No Toast data loaded yet.</p>
          <p className="text-dark-300 text-sm">
            Once this operator&apos;s Toast export is ingested, their report appears here automatically.
          </p>
        </div>
      </Shell>
    );
  }

  const cards: { label: string; value: string }[] = [
    { label: 'Total net sales', value: usd(report.totalNetSales) },
    { label: 'Locations', value: String(report.locationCount) },
  ];
  if (report.totalGuests != null) cards.push({ label: 'Guests', value: count(report.totalGuests) });
  if (report.totalVoids != null) cards.push({ label: 'Voids', value: usd(report.totalVoids) });
  if (report.totalDiscounts != null) cards.push({ label: 'Discounts', value: usd(report.totalDiscounts) });

  return (
    <Shell title={report.operatorName}>
      <p className="text-dark-200 -mt-4 mb-8">
        Net sales by location · {prettyDate(report.periodStart)} – {prettyDate(report.periodEnd)}
      </p>

      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 mb-10">
        {cards.map((c) => (
          <div key={c.label} className="bg-dark-700 rounded-xl p-5 border border-dark-600">
            <p className="text-dark-300 text-sm mb-1">{c.label}</p>
            <p className="text-2xl font-bold text-white">{c.value}</p>
          </div>
        ))}
      </div>

      <div className="bg-dark-700 rounded-xl border border-dark-600 overflow-hidden mb-8">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-dark-600 text-dark-300 text-sm">
              <th className="px-5 py-3 font-medium">#</th>
              <th className="px-5 py-3 font-medium">Location</th>
              <th className="px-5 py-3 font-medium">Market</th>
              <th className="px-5 py-3 font-medium text-right">Net sales</th>
            </tr>
          </thead>
          <tbody>
            {report.locations.map((loc, i) => (
              <tr key={loc.name} className="border-b border-dark-600/60 last:border-0">
                <td className="px-5 py-3 text-dark-400">{i + 1}</td>
                <td className="px-5 py-3 text-white">{loc.name}</td>
                <td className="px-5 py-3 text-dark-200">
                  {loc.city}, {loc.state}
                </td>
                <td className="px-5 py-3 text-right text-gold-300 font-semibold tabular-nums">{usd(loc.netSales)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="bg-dark-700/50 rounded-xl border border-dark-600 p-5 mb-6">
        <p className="text-white font-semibold mb-2 text-sm">What this is — and isn&apos;t</p>
        <ul className="text-dark-300 text-sm space-y-1 list-disc list-inside">
          <li>Every number is queried live from Toast data at the moment this page loads.</li>
          <li>Nothing here is estimated, projected, or generated by AI.</li>
          <li>
            Food / labor / prime cost % are <span className="text-dark-100">not connected yet</span> for these
            locations, so they are left out rather than guessed.
          </li>
        </ul>
      </div>

      <p className="text-dark-400 text-xs">
        Source: your POS data, reconciled across all locations · Last data refresh{' '}
        {report.lastIngest ? prettyDate(report.lastIngest) : '—'} · Rendered{' '}
        {new Date(report.generatedAt).toLocaleString('en-US')}
      </p>
    </Shell>
  );
}
