import Image from 'next/image';
import Link from 'next/link';
import { SELECTED_SITES_BASE_URL as APP } from '@/lib/selectedSites';
import styles from './OwnerHome.module.css';

const jobs = [
 ['01', 'Vendor prices', 'What went up on my invoice?', 'Compare the same SKU and pack across two invoices. See the change beside the original lines.', 'Two invoices from the same vendor', '/check/invoices', 'Check invoice prices'],
 ['02', 'Labor drift', 'Why did the shift run over?', 'Compare scheduled hours with the time clock. Find the difference before deciding what needs to change.', 'A schedule and matching time clock report', '/check/labor', 'Check labor drift'],
 ['03', 'Recipe costs', 'What does this plate cost now?', 'Connect ingredient costs to recipe quantities. See what price changes mean for the food you serve.', 'A recipe and ingredient purchase prices', '/check/menu', 'Check a recipe'],
];
const faq = [
 ['Do I need to connect my POS?', 'Start with reports and invoices you already have. No POS connection is required to try the checks. When a source is unclear, we ask for the specific missing detail.'],
 ['What can one invoice tell me?', 'One readable invoice can give you an organized summary. A price comparison needs another comparable invoice. Unknown pack sizes stay unresolved until you confirm them.'],
 ['Will you guess a number?', 'Missing information should stay missing. Comparisons need matching products, units and dates. Review the source and flagged uncertainty before acting.'],
 ['Is the first seat really free?', 'The first owner seat is free for one restaurant, with pilot usage limits. Additional manager seats are planned as paid options. We will explain availability and pricing before you commit.'],
 ['Who sees my restaurant files?', 'Sign in to One Seat before uploading private documents. Keep employee and customer details out of public examples. Our privacy policy explains how information is handled.'],
];
export default function OwnerHome() {
 return <main className={styles.page}>
  <a className={styles.skip} href="#checks">Skip to the checks</a>
  <header className={styles.header}><Link className={styles.brand} href="/" aria-label="Never86 home"><b>86</b> Never86’d</Link><nav aria-label="Main navigation"><a href="#checks">The checks</a><a href="#demo">Watch it work</a><a href="#story">Built by an operator</a></nav><a className={styles.signIn} href={`${APP}/seat`}>Open my seat ↗</a></header>
  <section className={styles.hero}><div><p className={styles.eyebrow}>FOR THE OWNER WEARING EVERY HAT</p><h1>You run the restaurant.<br/><span>Let’s check the numbers.</span></h1><p className={styles.intro}>The invoice that crept up. The shift that ran long. The plate that costs more to make. Start with one. See the evidence. Know your next move.</p><div className={styles.actions}><a href="#checks" className={styles.primary}>Find my first check ↗</a><a href="#demo" className={styles.secondary}>Watch the 68 second demo ▷</a></div><p className={styles.note}>First owner seat free · No card to start · Your existing reports</p></div>
   <div className={styles.receipt}><div className={styles.receiptTop}><b>N86</b><span>YOUR INVOICE CHECK</span><small>FICTIONAL EXAMPLE</small></div><p className={styles.eyebrow}>SAME VENDOR · SAME SKU · SAME PACK</p><h2>Your olive oil went up.</h2><div className={styles.prices}><div><small>Previous case</small><strong>$68.40</strong></div><span>→</span><div><small>Latest case</small><strong>$79.20</strong></div></div><div className={styles.delta}><strong>+$10.80 <small>per case</small></strong><b>+15.8%</b></div><div className={styles.next}><small>ONE NEXT MOVE</small><p>Ask your rep what changed before the next order.</p></div><details><summary>Show the math and source rules <span>+</span></summary><p>$79.20 − $68.40 = $10.80. $10.80 ÷ $68.40 = 15.8% rounded. This example assumes the same product and pack. It is a price increase, not money recovered.</p></details></div>
  </section>
  <div className={styles.belief}><small>NO CFO. NO BACK OFFICE. STILL YOUR NUMBERS.</small><p>Built by Myke Mueller, for the operators doing it all.</p></div>
  <section className={styles.section} id="checks"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>ONE SMALL START</p><h2>What’s costing you today?</h2></div><p>Pick the problem you recognize.<br/>Bring what you already have.</p></div><div className={styles.jobs}>{jobs.map(([n,label,title,copy,need,href,action])=><Link className={styles.job} key={n} href={href}><div className={styles.jobTop}><span>{n} · {label}</span><span>↗</span></div><h3>{title}</h3><p>{copy}</p><div className={styles.need}><small>BRING THIS</small>{need}</div><strong>{action} →</strong></Link>)}</div><p className={styles.note}>Source first. Questions when needed. You decide what to do next.</p></section>
  <section className={styles.demo} id="demo"><div><p className={styles.eyebrow}>SEE THE ACTUAL EXPERIENCE</p><h2>Less setup.<br/>More “now I see it.”</h2><p>Watch one check from the first screen to the evidence. Then try the tool that fits your day.</p><a className={styles.primary} href="#checks">Try a free check ↗</a></div><div><video className={styles.video} controls playsInline preload="none" poster="/media/never86-landscape-v24-poster.jpg"><source src="/media/never86-landscape-v24.mp4" type="video/mp4"/><track kind="captions" src="/media/never86-landscape-v24.vtt" srcLang="en" label="English" default/>Your browser cannot play this video.</video><p className={styles.caption}>68 seconds · Real product screens · Fictional sample documents · AI narration</p><a href={`${APP}/try/watch`} className={styles.videoLink}>Open the full demo page ↗</a></div></section>
  <section className={styles.story} id="story"><div className={styles.portrait}><Image src="/team/mm.jpg" alt="Myke Mueller, founder of Never86’d" fill sizes="(max-width: 700px) 90vw, 340px"/><span>MYKE MUELLER<br/><small>Operator. Founder. Still in the work.</small></span></div><div><p className={styles.eyebrow}>BUILT INSIDE THE WORK</p><h2>For all of us without<br/>a CFO or an office staff.</h2><p>Myke built Never86’d for the people wearing too many hats. You shouldn’t need another person in the office just to understand what changed in your restaurant.</p><small>Myke Mueller · Community Tap &amp; Pizza · Fort Dodge, Iowa</small><br/><Link href="/story">Meet the operator behind it ↗</Link></div></section>
  <section className={styles.faq}><div><p className={styles.eyebrow}>FAIR QUESTIONS</p><h2>Before you start.</h2><p>No new vocabulary required.</p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className={styles.finalCta}><p className={styles.eyebrow}>YOUR NEXT TEN MINUTES</p><h2>Bring one problem.<br/>Leave with a clearer next move.</h2><div className={styles.actions}><a href="#checks" className={styles.primary}>Choose my check ↗</a><Link href="/contact" className={styles.secondary}>Want a hand? Leave your email ↗</Link></div><p className={styles.note}>Trying a check is optional. Sharing your email is optional too.</p></section>
  <footer className={styles.footer}><Link href="/" className={styles.brand}>Never86’d</Link><p>Built by an operator. For the rest of us.</p><nav aria-label="Footer"><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><a href={`${APP}/seat`}>My seat ↗</a></nav></footer>
 </main>;
}
