import Image from 'next/image';
import Link from 'next/link';
import {
  GOLD_MOZZARELLA,
  ONE_SEAT_EQUALS,
  ONE_SEAT_ICP,
  money,
  pctLabel,
} from '@/lib/oneSeatPublicWin';
import { ONE_SEAT_PATHS } from '@/lib/selectedSites';
import styles from './OwnerHome.module.css';

const jobs = [
 ['01', 'Vendor prices', 'What went up on my invoice?', 'Compare the same SKU and pack across two invoices. See the change beside the original lines.', 'Two invoices from the same vendor', ONE_SEAT_PATHS.checkInvoices, 'Check invoice prices'],
 ['02', 'Labor drift', 'Why did the shift run over?', 'Compare scheduled hours with the time clock. Find the difference before deciding what needs to change.', 'A schedule and matching time clock report', ONE_SEAT_PATHS.checkLabor, 'Check labor drift'],
 ['03', 'Recipe costs', 'What does this plate cost now?', 'Connect ingredient costs to recipe quantities. See what price changes mean for the food you serve.', 'A recipe and ingredient purchase prices', ONE_SEAT_PATHS.checkMenu, 'Check a recipe'],
];
const faq = [
 ['Do I need to connect my POS?', 'Start with reports and invoices you already have. No POS connection is required to try the checks. When a source is unclear, we ask for the specific missing detail.'],
 ['What can one invoice tell me?', 'One readable invoice can give you an organized summary. A price comparison needs another comparable invoice. Unknown pack sizes stay unresolved until you confirm them.'],
 ['Will you guess a number?', 'Missing information should stay missing. Comparisons need matching products, units and dates. Review the source and flagged uncertainty before acting.'],
 ['Is the first seat really free?', 'The first owner seat is free for one restaurant, with pilot usage limits. Additional manager seats are planned as paid options. We will explain availability and pricing before you commit.'],
 ['Who sees my restaurant files?', 'Sign in to One Seat on never86.ai before uploading private documents. Keep employee and customer details out of public examples. Our privacy policy explains how information is handled.'],
 ['Do I have to start in ChatGPT?', 'No. The public operator door and the free owner seat live on never86.ai. Grok can explain a card after the formula runs. This is not a Grok-resale product and not a ChatGPT onboarding path.'],
];
export default function OwnerHome() {
 return <main className={styles.page}>
  <a className={styles.skip} href="#checks">Skip to the checks</a>
  <header className={styles.header}><Link className={styles.brand} href="/" aria-label="Never86 home"><b>86</b> Never86’d</Link><nav aria-label="Main navigation"><a href="#checks">The checks</a><Link href={ONE_SEAT_PATHS.try}>Try the sample</Link><a href="#story">Built by an operator</a></nav><Link className={styles.signIn} href={ONE_SEAT_PATHS.onboard}>Claim free owner seat</Link></header>
  <section className={styles.hero}><div><p className={styles.eyebrow}>ONE SEAT · ACTION SHIFT · {ONE_SEAT_ICP.toUpperCase()}</p><h1>You run the restaurant.<br/><span>Let’s check the numbers.</span></h1><p className={styles.intro}>{ONE_SEAT_EQUALS}. Drop last week’s papers, get one owned next move, prove it tonight. The seat lives on never86.ai. Grok can explain the card. Formulas decide the dollars.</p><div className={styles.actions}><Link href={ONE_SEAT_PATHS.try} className={styles.primary}>Try the two-invoice win ↗</Link><Link href={ONE_SEAT_PATHS.onboard} className={styles.secondary}>Claim free owner seat</Link></div><p className={styles.note}>First owner seat free · No card to start · Your existing reports · No ChatGPT sign-in</p></div>
   <div className={styles.receipt}><div className={styles.receiptTop}><b>N86</b><span>YOUR INVOICE CHECK</span><small>FICTIONAL EXAMPLE</small></div><p className={styles.eyebrow}>SAME VENDOR · SAME SKU · SAME PACK</p><h2>Same cheese. Higher price.</h2><div className={styles.prices}><div><small>Previous case</small><strong>{money(GOLD_MOZZARELLA.priorPrice)}</strong></div><span>→</span><div><small>Latest case</small><strong>{money(GOLD_MOZZARELLA.currentPrice)}</strong></div></div><div className={styles.delta}><strong>+{money(GOLD_MOZZARELLA.delta)} <small>per case</small></strong><b>+{pctLabel(GOLD_MOZZARELLA.driftPct)}</b></div><div className={styles.next}><small>ONE NEXT MOVE</small><p>{GOLD_MOZZARELLA.nextMove}</p></div><details><summary>Show the math and source rules <span>+</span></summary><p>{money(GOLD_MOZZARELLA.currentPrice)} − {money(GOLD_MOZZARELLA.priorPrice)} = {money(GOLD_MOZZARELLA.delta)}. {money(GOLD_MOZZARELLA.delta)} ÷ {money(GOLD_MOZZARELLA.priorPrice)} = {pctLabel(GOLD_MOZZARELLA.driftPct)} rounded. Same product and pack. {GOLD_MOZZARELLA.claimBoundary} It is a price increase, not money recovered.</p></details></div>
  </section>
  <div className={styles.belief}><small>NO CFO. NO BACK OFFICE. STILL YOUR NUMBERS.</small><p>Built by Myke Mueller, for {ONE_SEAT_ICP} wearing every hat.</p></div>
  <section className={styles.section} id="checks"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>ONE SMALL START</p><h2>What’s costing you today?</h2></div><p>Pick the problem you recognize.<br/>Bring what you already have.</p></div><div className={styles.jobs}>{jobs.map(([n,label,title,copy,need,href,action])=><Link className={styles.job} key={n} href={href}><div className={styles.jobTop}><span>{n} · {label}</span><span>↗</span></div><h3>{title}</h3><p>{copy}</p><div className={styles.need}><small>BRING THIS</small>{need}</div><strong>{action} →</strong></Link>)}</div><p className={styles.note}>Source first. Questions when needed. You decide what to do next.</p></section>
  <section className={styles.demo} id="demo"><div><p className={styles.eyebrow}>SEE THE ACTUAL EXPERIENCE</p><h2>Less setup.<br/>More “now I see it.”</h2><p>Watch one check from the first screen to the evidence. Then run the two-invoice win on this site.</p><Link className={styles.primary} href={ONE_SEAT_PATHS.try}>Try the sample ↗</Link></div><div><video className={styles.video} controls playsInline preload="none" poster="/media/never86-landscape-v24-poster.jpg"><source src="/media/never86-landscape-v24.mp4" type="video/mp4"/><track kind="captions" src="/media/never86-landscape-v24.vtt" srcLang="en" label="English" default/>Your browser cannot play this video.</video><p className={styles.caption}>68 seconds · Real product screens · Fictional sample documents · AI narration</p><Link href={ONE_SEAT_PATHS.tryWatch} className={styles.videoLink}>Open the full demo page ↗</Link></div></section>
  <section className={styles.story} id="story"><div className={styles.portrait}><Image src="/team/mm.jpg" alt="Myke Mueller, founder of Never86’d" fill sizes="(max-width: 700px) 90vw, 340px"/><span>MYKE MUELLER<br/><small>Operator. Founder. Still in the work.</small></span></div><div><p className={styles.eyebrow}>BUILT INSIDE THE WORK</p><h2>For all of us without<br/>a CFO or an office staff.</h2><p>Myke built Never86’d for the people wearing too many hats. You shouldn’t need another person in the office just to understand what changed in your restaurant.</p><small>Myke Mueller · Community Tap &amp; Pizza · Fort Dodge, Iowa</small><br/><Link href="/story">Meet the operator behind it ↗</Link></div></section>
  <section className={styles.faq}><div><p className={styles.eyebrow}>FAIR QUESTIONS</p><h2>Before you start.</h2><p>No new vocabulary required.</p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className={styles.finalCta}><p className={styles.eyebrow}>YOUR NEXT TEN MINUTES</p><h2>Bring one problem.<br/>Leave with a clearer next move.</h2><div className={styles.actions}><Link href={ONE_SEAT_PATHS.try} className={styles.primary}>Try the two-invoice win ↗</Link><Link href={ONE_SEAT_PATHS.onboard} className={styles.secondary}>Claim free owner seat ↗</Link></div><p className={styles.note}>Trying a check is optional. Sharing your email is optional too. The seat stays on never86.ai.</p></section>
  <footer className={styles.footer}><Link href="/" className={styles.brand}>Never86’d</Link><p>Built by an operator. For the rest of us.</p><nav aria-label="Footer"><Link href={ONE_SEAT_PATHS.contact}>Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href={ONE_SEAT_PATHS.login}>Sign in</Link></nav></footer>
 </main>;
}
