-- Action Shift workforce and checklist foundation.
-- Private employee records belong in the tenant database, never in Git.

-- Composite tenant keys let every child foreign key prove that its parent
-- belongs to the same operator. The existing location id remains globally
-- unique; this additional key is for tenant-safe references.
create unique index if not exists operator_locations_operator_id_id_unique
  on public.operator_locations (operator_id, id);

create table public.operator_staff_seats (
  id uuid primary key default gen_random_uuid(),
  operator_id integer not null references public.operator_users(id) on delete cascade,
  default_location_id integer,
  auth_subject uuid unique,
  display_name text not null,
  email text,
  job_title text,
  status text not null default 'invited'
    check (status in ('invited', 'active', 'inactive', 'archived')),
  hired_on date,
  terminated_on date,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (operator_id, id),
  foreign key (operator_id, default_location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  check (terminated_on is null or hired_on is null or terminated_on >= hired_on)
);

create table public.action_shift_role_assignments (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  seat_id uuid not null,
  location_id integer,
  role_key text not null
    check (role_key in ('owner', 'general_manager', 'manager', 'kitchen_manager', 'shift_lead', 'cook', 'server', 'bartender', 'driver', 'dishwasher', 'staff')),
  is_primary boolean not null default false,
  active_from date not null default current_date,
  active_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (operator_id, seat_id)
    references public.operator_staff_seats(operator_id, id) on delete cascade,
  foreign key (operator_id, location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  check (active_until is null or active_until >= active_from)
);

-- PostgreSQL 14-compatible uniqueness for global and location-scoped roles.
create unique index action_shift_roles_global_scope_unique
  on public.action_shift_role_assignments (operator_id, seat_id, role_key, active_from)
  where location_id is null;
create unique index action_shift_roles_location_scope_unique
  on public.action_shift_role_assignments (operator_id, seat_id, location_id, role_key, active_from)
  where location_id is not null;

create table public.action_shift_identity_links (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  seat_id uuid not null,
  system_kind text not null
    check (system_kind in ('pos', 'time_clock', 'scheduling', 'checklist', 'identity', 'other')),
  provider_key text not null,
  external_worker_id text not null,
  external_location_id text,
  active boolean not null default true,
  last_verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (operator_id, provider_key, external_worker_id),
  foreign key (operator_id, seat_id)
    references public.operator_staff_seats(operator_id, id) on delete cascade
);

create table public.action_shift_schedule_shifts (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  location_id integer not null,
  seat_id uuid,
  provider_key text not null,
  external_shift_id text not null,
  external_worker_id text,
  position_name text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'worked', 'missed', 'cancelled')),
  source_updated_at timestamptz,
  imported_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (operator_id, provider_key, external_shift_id),
  unique (operator_id, id),
  foreign key (operator_id, location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  foreign key (operator_id, seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict,
  check (ends_at > starts_at)
);

create table public.action_shift_checklist_templates (
  id uuid primary key default gen_random_uuid(),
  operator_id integer not null references public.operator_users(id) on delete cascade,
  location_id integer,
  role_key text,
  name text not null,
  shift_phase text not null
    check (shift_phase in ('open', 'pre_shift', 'during_shift', 'handoff', 'close', 'weekly')),
  version integer not null default 1 check (version > 0),
  status text not null default 'draft'
    check (status in ('draft', 'active', 'retired')),
  effective_from date,
  effective_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (operator_id, id),
  foreign key (operator_id, location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  check (effective_until is null or effective_from is null or effective_until >= effective_from)
);

create table public.action_shift_checklist_steps (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  template_id uuid not null,
  step_order integer not null check (step_order > 0),
  instruction text not null,
  evidence_type text not null default 'attestation'
    check (evidence_type in ('attestation', 'photo', 'document', 'number', 'temperature', 'signature', 'none')),
  is_required boolean not null default true,
  escalation_minutes integer check (escalation_minutes is null or escalation_minutes > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (template_id, step_order),
  unique (operator_id, id),
  foreign key (operator_id, template_id)
    references public.action_shift_checklist_templates(operator_id, id) on delete cascade
);

create table public.action_shift_checklist_runs (
  id uuid primary key default gen_random_uuid(),
  operator_id integer not null references public.operator_users(id) on delete cascade,
  location_id integer not null,
  template_id uuid not null,
  assigned_seat_id uuid,
  schedule_shift_id bigint,
  run_key text not null,
  business_date date not null,
  status text not null default 'assigned'
    check (status in ('assigned', 'in_progress', 'submitted', 'verified', 'needs_attention', 'waived')),
  due_at timestamptz,
  started_at timestamptz,
  submitted_at timestamptz,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (operator_id, run_key),
  unique (operator_id, id),
  foreign key (operator_id, location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  foreign key (operator_id, template_id)
    references public.action_shift_checklist_templates(operator_id, id) on delete restrict,
  foreign key (operator_id, assigned_seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict,
  foreign key (operator_id, schedule_shift_id)
    references public.action_shift_schedule_shifts(operator_id, id) on delete restrict,
  check (submitted_at is null or started_at is null or submitted_at >= started_at),
  check (verified_at is null or submitted_at is null or verified_at >= submitted_at)
);

create table public.action_shift_step_receipts (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  run_id uuid not null,
  step_id bigint not null,
  actor_seat_id uuid,
  status text not null default 'complete'
    check (status in ('complete', 'skipped', 'failed', 'needs_attention')),
  evidence_uri text,
  value_text text,
  notes text,
  observed_at timestamptz not null default now(),
  verified_by_seat_id uuid,
  verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_id, step_id),
  foreign key (operator_id, run_id)
    references public.action_shift_checklist_runs(operator_id, id) on delete cascade,
  foreign key (operator_id, step_id)
    references public.action_shift_checklist_steps(operator_id, id) on delete restrict,
  foreign key (operator_id, actor_seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict,
  foreign key (operator_id, verified_by_seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict
);

create table public.action_shift_feedback (
  id bigint generated by default as identity primary key,
  operator_id integer not null references public.operator_users(id) on delete cascade,
  location_id integer,
  run_id uuid,
  actor_seat_id uuid,
  source_kind text not null
    check (source_kind in ('action', 'checklist', 'briefing', 'integration', 'model_output')),
  source_ref text,
  verdict text not null
    check (verdict in ('accepted', 'rejected', 'completed', 'failed', 'corrected', 'needs_review')),
  correction text,
  outcome jsonb not null default '{}'::jsonb,
  learning_status text not null default 'candidate'
    check (learning_status in ('candidate', 'approved', 'rejected', 'applied')),
  reviewed_by_seat_id uuid,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  foreign key (operator_id, location_id)
    references public.operator_locations(operator_id, id) on delete restrict,
  foreign key (operator_id, run_id)
    references public.action_shift_checklist_runs(operator_id, id) on delete restrict,
  foreign key (operator_id, actor_seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict,
  foreign key (operator_id, reviewed_by_seat_id)
    references public.operator_staff_seats(operator_id, id) on delete restrict
);

-- Foreign-key and tenant/RLS lookup indexes.
create index operator_staff_seats_operator_status_idx
  on public.operator_staff_seats (operator_id, status);
create index operator_staff_seats_operator_location_idx
  on public.operator_staff_seats (operator_id, default_location_id);
create index action_shift_roles_operator_seat_idx
  on public.action_shift_role_assignments (operator_id, seat_id, active_until);
create index action_shift_roles_operator_location_role_idx
  on public.action_shift_role_assignments (operator_id, location_id, role_key);
create index action_shift_identity_seat_idx
  on public.action_shift_identity_links (operator_id, seat_id, active);
create index action_shift_schedule_location_start_idx
  on public.action_shift_schedule_shifts (operator_id, location_id, starts_at);
create index action_shift_schedule_seat_start_idx
  on public.action_shift_schedule_shifts (operator_id, seat_id, starts_at);
create index action_shift_templates_scope_idx
  on public.action_shift_checklist_templates (operator_id, location_id, role_key, status);
create index action_shift_steps_operator_template_idx
  on public.action_shift_checklist_steps (operator_id, template_id, step_order);
create index action_shift_runs_location_date_idx
  on public.action_shift_checklist_runs (operator_id, location_id, business_date, status);
create index action_shift_runs_seat_due_idx
  on public.action_shift_checklist_runs (operator_id, assigned_seat_id, due_at);
create index action_shift_runs_template_idx
  on public.action_shift_checklist_runs (template_id);
create index action_shift_runs_schedule_idx
  on public.action_shift_checklist_runs (schedule_shift_id);
create index action_shift_receipts_run_idx
  on public.action_shift_step_receipts (operator_id, run_id);
create index action_shift_receipts_step_idx
  on public.action_shift_step_receipts (step_id);
create index action_shift_receipts_actor_idx
  on public.action_shift_step_receipts (actor_seat_id);
create index action_shift_receipts_verifier_idx
  on public.action_shift_step_receipts (verified_by_seat_id);
create index action_shift_feedback_review_idx
  on public.action_shift_feedback (operator_id, learning_status, created_at desc);
create index action_shift_feedback_run_idx
  on public.action_shift_feedback (run_id);
create index action_shift_feedback_actor_idx
  on public.action_shift_feedback (actor_seat_id);
create index action_shift_feedback_reviewer_idx
  on public.action_shift_feedback (reviewed_by_seat_id);

-- Browser clients receive no anonymous access. Authenticated access is still
-- constrained by RLS; service_role remains the controlled integration path.
revoke all on table
  public.operator_staff_seats,
  public.action_shift_role_assignments,
  public.action_shift_identity_links,
  public.action_shift_schedule_shifts,
  public.action_shift_checklist_templates,
  public.action_shift_checklist_steps,
  public.action_shift_checklist_runs,
  public.action_shift_step_receipts,
  public.action_shift_feedback
from anon;

-- Workforce and evidence records use status/retention fields instead of client
-- deletion. Destructive cleanup remains a controlled service-role operation.
grant select, insert, update on table
  public.operator_staff_seats,
  public.action_shift_role_assignments,
  public.action_shift_identity_links,
  public.action_shift_schedule_shifts,
  public.action_shift_checklist_templates,
  public.action_shift_checklist_steps,
  public.action_shift_checklist_runs,
  public.action_shift_step_receipts,
  public.action_shift_feedback
to authenticated;

grant usage, select on sequence
  public.action_shift_role_assignments_id_seq,
  public.action_shift_identity_links_id_seq,
  public.action_shift_schedule_shifts_id_seq,
  public.action_shift_checklist_steps_id_seq,
  public.action_shift_step_receipts_id_seq,
  public.action_shift_feedback_id_seq
to authenticated;

alter table public.operator_staff_seats enable row level security;
alter table public.action_shift_role_assignments enable row level security;
alter table public.action_shift_identity_links enable row level security;
alter table public.action_shift_schedule_shifts enable row level security;
alter table public.action_shift_checklist_templates enable row level security;
alter table public.action_shift_checklist_steps enable row level security;
alter table public.action_shift_checklist_runs enable row level security;
alter table public.action_shift_step_receipts enable row level security;
alter table public.action_shift_feedback enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'operator_staff_seats',
    'action_shift_role_assignments',
    'action_shift_identity_links',
    'action_shift_schedule_shifts',
    'action_shift_checklist_templates',
    'action_shift_checklist_steps',
    'action_shift_checklist_runs',
    'action_shift_step_receipts',
    'action_shift_feedback'
  ] loop
    execute format(
      'create policy operator_isolation on public.%I for all to authenticated using (operator_id = (select public.current_operator_id())) with check (operator_id = (select public.current_operator_id()))',
      table_name
    );
  end loop;
end $$;

comment on table public.operator_staff_seats is
  'Private Action Shift seats. Live employee names, emails, and auth subjects are stored here, never in source control.';
comment on table public.action_shift_role_assignments is
  'Effective-dated, location-aware roles that drive worker-specific Action Shift access and checklists.';
comment on table public.action_shift_identity_links is
  'Tenant-scoped mapping from POS, time-clock, scheduling, checklist, and identity-provider worker IDs to staff seats.';
comment on table public.action_shift_schedule_shifts is
  'Normalized scheduled or worked shifts imported from approved scheduling and time-clock sources.';
comment on table public.action_shift_checklist_templates is
  'Versioned role/location checklist definitions for Action Shift.';
comment on table public.action_shift_checklist_steps is
  'Ordered checklist instructions and evidence requirements.';
comment on table public.action_shift_checklist_runs is
  'Assigned checklist instances for a store, business date, staff seat, and optional scheduled shift.';
comment on table public.action_shift_step_receipts is
  'Evidence-backed completion receipts; evidence_uri must point to private tenant-scoped storage.';
comment on table public.action_shift_feedback is
  'Human outcomes and corrections for the mini-brain learning queue; candidates require review before application.';
