import type { Metadata } from 'next';
import Link from 'next/link';
import scenes from '../../../../marketing/demo-launch/owner-seat-story.json';
import s from '../brand/page.module.css';
export const metadata: Metadata = { title: 'Never86 owner seat: video and words', robots: { index: false, follow: true } };
export default function ScriptPage() {
 return <main className={s.page}><header className={s.header}><Link href="/demo/operator" className={s.brand}><span>86</span>Never86’d</Link><span>THE OWNER SEAT</span></header>
 <section className={s.intro}><p className={s.eyebrow}>THE WORDS. THE SCREENS. THE POINT.</p><h1>Know what went up.<br/><em>Before you order again.</em></h1><p>For the operator running one to five places and wearing too many hats. Start with two invoices and see what went up since last week. Your first location and owner seat are free. The full app stays in view.</p><p style={{marginTop:24}}><a href="https://drive.google.com/file/d/1CeoCCSufKfA63uKxhxl-jB8CINJb77GJ/view">Watch the full app video ↗</a> · <Link href="/demo/operator">Try the owner seat ↗</Link></p></section>
 <section aria-label="The video transcript">{scenes.map((scene,index)=>{const start=scenes.slice(0,index).reduce((total,item)=>total+item.seconds,0); const end=start+scene.seconds;return <article key={scene.id} style={{borderTop:'1px solid #ded7cc',padding:'26px 0'}}><p className={s.eyebrow}>{start} TO {end} SECONDS</p><h2 style={{fontSize:24,lineHeight:1.4,margin:'12px 0'}}>{scene.caption[0]}<br/>{scene.caption[1]}</h2><p style={{color:'#6b6660',maxWidth:800}}>{scene.screen}</p><details style={{marginTop:14}}><summary style={{cursor:'pointer',minHeight:44}}>Spoken version for Myke</summary><p>{scene.voice}</p></details></article>})}</section>
 <section className={s.rules}><div><p className={s.eyebrow}>LESS TO TYPE. LESS TO FIGURE OUT.</p><h2>The next step is prepared.</h2><p>The question, person and due time are already there. Review once. Change only what needs changing. The example checks food cost against an editable target.</p></div><div><p className={s.eyebrow}>20 SECOND VERSION</p><p style={{marginTop:14}}>Two invoices. What went up this week? Catch the price change before the next order. That increase adds 10¢ to this cheese pizza. Food cost is 30.6%. Your target is 30%. Your first location and owner seat are free. Vendors. Labor. Pours. Try Never86.</p></div></section>
 <footer className={s.footer}><p>Product preview with fictional restaurant records. The video is captioned and silent, using actual UI stills. The spoken version is a script. The recipe uses 8 oz of cheese, $3.60 in other ingredients and a $16 menu price before tax. The 30% target is an example, not a restaurant benchmark. Approval stays in the preview tab. Nothing is sent.</p><Link href="/demo/operator">Open the owner seat →</Link></footer></main>;
}
