-- 0004_operator_auth.sql
--
-- Per-operator login credentials for the operator portal (/login -> /dashboard).
-- One row per login: an email + scrypt password hash mapped to an
-- operator_users.id. A logged-in operator only ever sees their own operator_id
-- (the id is carried in a signed session cookie, never chosen from the URL),
-- so this replaces the old single shared REPORTS_PASSWORD for customers.
--
-- Apply to Supabase project `never86` (public schema, same DB as the Toast data).

begin;

create table if not exists public.operator_credentials (
  id            bigint generated by default as identity primary key,
  operator_id   integer     not null references public.operator_users(id) on delete cascade,
  email         text        not null,
  password_hash text        not null,
  created_at    timestamptz not null default now(),
  last_login_at timestamptz
);

-- One login per email (case-insensitive).
create unique index if not exists operator_credentials_email_key
  on public.operator_credentials (lower(email));

create index if not exists operator_credentials_operator_id_idx
  on public.operator_credentials (operator_id);

commit;

-- To create a login, use the admin page at /admin/operator-logins
-- (or POST /api/admin/operator-credentials with the admin cookie). It hashes
-- the password with scrypt before insert — never store a plaintext password here.
