-- 0005_operator_activation.sql
--
-- Monday gate (#118): one-time expiring email activation tokens.
-- Never store or email a plaintext starter password.
-- Applied to Supabase project never86 (ops) when the project is ACTIVE.
--
-- Proven live columns used by activation (from applied sql/0003 + sql/0004):
--   operator_users(id, name, restaurant_name, email)
--   operator_locations(id, operator_id, name, city, state)
--   operator_credentials(id, operator_id, email, password_hash, created_at, last_login_at)

begin;

create table if not exists public.operator_activation_tokens (
  id              bigint generated by default as identity primary key,
  email           text        not null,
  restaurant_name text        not null,
  operator_name   text,
  token_hash      text        not null,
  source_page     text,
  consent_at      timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  expires_at      timestamptz not null,
  consumed_at     timestamptz,
  consumed_operator_id integer references public.operator_users(id) on delete set null,
  request_ip      text,
  user_agent      text
);

create unique index if not exists operator_activation_tokens_hash_key
  on public.operator_activation_tokens (token_hash);

create index if not exists operator_activation_tokens_email_created_idx
  on public.operator_activation_tokens (lower(email), created_at desc);

commit;
